ALTER TABLE LeagueSeason ADD COLUMN competitionType TEXT NOT NULL DEFAULT 'ROUND_ROBIN';
ALTER TABLE LeagueSeason ADD COLUMN initialBudget INTEGER NOT NULL DEFAULT 1000000;
ALTER TABLE LeagueSeason ADD COLUMN tieBreakers TEXT NOT NULL DEFAULT '["TD_DIFF", "CAS_DIFF"]';
ALTER TABLE LeagueSeason ADD COLUMN startDate DATETIME;
ALTER TABLE LeagueSeason ADD COLUMN endDate DATETIME;
ALTER TABLE LeagueSeason ADD COLUMN description TEXT;
