
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReferenceData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReferenceData
 * 
 */
export type ReferenceDataModel = runtime.Types.Result.DefaultSelection<Prisma.$ReferenceDataPayload>

export type AggregateReferenceData = {
  _count: ReferenceDataCountAggregateOutputType | null
  _avg: ReferenceDataAvgAggregateOutputType | null
  _sum: ReferenceDataSumAggregateOutputType | null
  _min: ReferenceDataMinAggregateOutputType | null
  _max: ReferenceDataMaxAggregateOutputType | null
}

export type ReferenceDataAvgAggregateOutputType = {
  order: number | null
}

export type ReferenceDataSumAggregateOutputType = {
  order: number | null
}

export type ReferenceDataMinAggregateOutputType = {
  id: string | null
  group: string | null
  key: string | null
  label: string | null
  order: number | null
  isActive: boolean | null
}

export type ReferenceDataMaxAggregateOutputType = {
  id: string | null
  group: string | null
  key: string | null
  label: string | null
  order: number | null
  isActive: boolean | null
}

export type ReferenceDataCountAggregateOutputType = {
  id: number
  group: number
  key: number
  label: number
  order: number
  isActive: number
  _all: number
}


export type ReferenceDataAvgAggregateInputType = {
  order?: true
}

export type ReferenceDataSumAggregateInputType = {
  order?: true
}

export type ReferenceDataMinAggregateInputType = {
  id?: true
  group?: true
  key?: true
  label?: true
  order?: true
  isActive?: true
}

export type ReferenceDataMaxAggregateInputType = {
  id?: true
  group?: true
  key?: true
  label?: true
  order?: true
  isActive?: true
}

export type ReferenceDataCountAggregateInputType = {
  id?: true
  group?: true
  key?: true
  label?: true
  order?: true
  isActive?: true
  _all?: true
}

export type ReferenceDataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReferenceData to aggregate.
   */
  where?: Prisma.ReferenceDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReferenceData to fetch.
   */
  orderBy?: Prisma.ReferenceDataOrderByWithRelationInput | Prisma.ReferenceDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReferenceDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReferenceData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReferenceData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReferenceData
  **/
  _count?: true | ReferenceDataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReferenceDataAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReferenceDataSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReferenceDataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReferenceDataMaxAggregateInputType
}

export type GetReferenceDataAggregateType<T extends ReferenceDataAggregateArgs> = {
      [P in keyof T & keyof AggregateReferenceData]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReferenceData[P]>
    : Prisma.GetScalarType<T[P], AggregateReferenceData[P]>
}




export type ReferenceDataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReferenceDataWhereInput
  orderBy?: Prisma.ReferenceDataOrderByWithAggregationInput | Prisma.ReferenceDataOrderByWithAggregationInput[]
  by: Prisma.ReferenceDataScalarFieldEnum[] | Prisma.ReferenceDataScalarFieldEnum
  having?: Prisma.ReferenceDataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReferenceDataCountAggregateInputType | true
  _avg?: ReferenceDataAvgAggregateInputType
  _sum?: ReferenceDataSumAggregateInputType
  _min?: ReferenceDataMinAggregateInputType
  _max?: ReferenceDataMaxAggregateInputType
}

export type ReferenceDataGroupByOutputType = {
  id: string
  group: string
  key: string
  label: string
  order: number
  isActive: boolean
  _count: ReferenceDataCountAggregateOutputType | null
  _avg: ReferenceDataAvgAggregateOutputType | null
  _sum: ReferenceDataSumAggregateOutputType | null
  _min: ReferenceDataMinAggregateOutputType | null
  _max: ReferenceDataMaxAggregateOutputType | null
}

type GetReferenceDataGroupByPayload<T extends ReferenceDataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReferenceDataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReferenceDataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReferenceDataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReferenceDataGroupByOutputType[P]>
      }
    >
  >



export type ReferenceDataWhereInput = {
  AND?: Prisma.ReferenceDataWhereInput | Prisma.ReferenceDataWhereInput[]
  OR?: Prisma.ReferenceDataWhereInput[]
  NOT?: Prisma.ReferenceDataWhereInput | Prisma.ReferenceDataWhereInput[]
  id?: Prisma.StringFilter<"ReferenceData"> | string
  group?: Prisma.StringFilter<"ReferenceData"> | string
  key?: Prisma.StringFilter<"ReferenceData"> | string
  label?: Prisma.StringFilter<"ReferenceData"> | string
  order?: Prisma.IntFilter<"ReferenceData"> | number
  isActive?: Prisma.BoolFilter<"ReferenceData"> | boolean
}

export type ReferenceDataOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  group?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type ReferenceDataWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  group_key?: Prisma.ReferenceDataGroupKeyCompoundUniqueInput
  AND?: Prisma.ReferenceDataWhereInput | Prisma.ReferenceDataWhereInput[]
  OR?: Prisma.ReferenceDataWhereInput[]
  NOT?: Prisma.ReferenceDataWhereInput | Prisma.ReferenceDataWhereInput[]
  group?: Prisma.StringFilter<"ReferenceData"> | string
  key?: Prisma.StringFilter<"ReferenceData"> | string
  label?: Prisma.StringFilter<"ReferenceData"> | string
  order?: Prisma.IntFilter<"ReferenceData"> | number
  isActive?: Prisma.BoolFilter<"ReferenceData"> | boolean
}, "id" | "group_key">

export type ReferenceDataOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  group?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  _count?: Prisma.ReferenceDataCountOrderByAggregateInput
  _avg?: Prisma.ReferenceDataAvgOrderByAggregateInput
  _max?: Prisma.ReferenceDataMaxOrderByAggregateInput
  _min?: Prisma.ReferenceDataMinOrderByAggregateInput
  _sum?: Prisma.ReferenceDataSumOrderByAggregateInput
}

export type ReferenceDataScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReferenceDataScalarWhereWithAggregatesInput | Prisma.ReferenceDataScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReferenceDataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReferenceDataScalarWhereWithAggregatesInput | Prisma.ReferenceDataScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ReferenceData"> | string
  group?: Prisma.StringWithAggregatesFilter<"ReferenceData"> | string
  key?: Prisma.StringWithAggregatesFilter<"ReferenceData"> | string
  label?: Prisma.StringWithAggregatesFilter<"ReferenceData"> | string
  order?: Prisma.IntWithAggregatesFilter<"ReferenceData"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"ReferenceData"> | boolean
}

export type ReferenceDataCreateInput = {
  id?: string
  group: string
  key: string
  label: string
  order?: number
  isActive?: boolean
}

export type ReferenceDataUncheckedCreateInput = {
  id?: string
  group: string
  key: string
  label: string
  order?: number
  isActive?: boolean
}

export type ReferenceDataUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  group?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ReferenceDataUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  group?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ReferenceDataCreateManyInput = {
  id?: string
  group: string
  key: string
  label: string
  order?: number
  isActive?: boolean
}

export type ReferenceDataUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  group?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ReferenceDataUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  group?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ReferenceDataGroupKeyCompoundUniqueInput = {
  group: string
  key: string
}

export type ReferenceDataCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  group?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type ReferenceDataAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type ReferenceDataMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  group?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type ReferenceDataMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  group?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type ReferenceDataSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}



export type ReferenceDataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  group?: boolean
  key?: boolean
  label?: boolean
  order?: boolean
  isActive?: boolean
}, ExtArgs["result"]["referenceData"]>

export type ReferenceDataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  group?: boolean
  key?: boolean
  label?: boolean
  order?: boolean
  isActive?: boolean
}, ExtArgs["result"]["referenceData"]>

export type ReferenceDataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  group?: boolean
  key?: boolean
  label?: boolean
  order?: boolean
  isActive?: boolean
}, ExtArgs["result"]["referenceData"]>

export type ReferenceDataSelectScalar = {
  id?: boolean
  group?: boolean
  key?: boolean
  label?: boolean
  order?: boolean
  isActive?: boolean
}

export type ReferenceDataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "group" | "key" | "label" | "order" | "isActive", ExtArgs["result"]["referenceData"]>

export type $ReferenceDataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReferenceData"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    group: string
    key: string
    label: string
    order: number
    isActive: boolean
  }, ExtArgs["result"]["referenceData"]>
  composites: {}
}

export type ReferenceDataGetPayload<S extends boolean | null | undefined | ReferenceDataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload, S>

export type ReferenceDataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReferenceDataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReferenceDataCountAggregateInputType | true
  }

export interface ReferenceDataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReferenceData'], meta: { name: 'ReferenceData' } }
  /**
   * Find zero or one ReferenceData that matches the filter.
   * @param {ReferenceDataFindUniqueArgs} args - Arguments to find a ReferenceData
   * @example
   * // Get one ReferenceData
   * const referenceData = await prisma.referenceData.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReferenceDataFindUniqueArgs>(args: Prisma.SelectSubset<T, ReferenceDataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReferenceDataClient<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReferenceData that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReferenceDataFindUniqueOrThrowArgs} args - Arguments to find a ReferenceData
   * @example
   * // Get one ReferenceData
   * const referenceData = await prisma.referenceData.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReferenceDataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReferenceDataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReferenceDataClient<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReferenceData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReferenceDataFindFirstArgs} args - Arguments to find a ReferenceData
   * @example
   * // Get one ReferenceData
   * const referenceData = await prisma.referenceData.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReferenceDataFindFirstArgs>(args?: Prisma.SelectSubset<T, ReferenceDataFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReferenceDataClient<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReferenceData that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReferenceDataFindFirstOrThrowArgs} args - Arguments to find a ReferenceData
   * @example
   * // Get one ReferenceData
   * const referenceData = await prisma.referenceData.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReferenceDataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReferenceDataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReferenceDataClient<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReferenceData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReferenceDataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReferenceData
   * const referenceData = await prisma.referenceData.findMany()
   * 
   * // Get first 10 ReferenceData
   * const referenceData = await prisma.referenceData.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const referenceDataWithIdOnly = await prisma.referenceData.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReferenceDataFindManyArgs>(args?: Prisma.SelectSubset<T, ReferenceDataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReferenceData.
   * @param {ReferenceDataCreateArgs} args - Arguments to create a ReferenceData.
   * @example
   * // Create one ReferenceData
   * const ReferenceData = await prisma.referenceData.create({
   *   data: {
   *     // ... data to create a ReferenceData
   *   }
   * })
   * 
   */
  create<T extends ReferenceDataCreateArgs>(args: Prisma.SelectSubset<T, ReferenceDataCreateArgs<ExtArgs>>): Prisma.Prisma__ReferenceDataClient<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReferenceData.
   * @param {ReferenceDataCreateManyArgs} args - Arguments to create many ReferenceData.
   * @example
   * // Create many ReferenceData
   * const referenceData = await prisma.referenceData.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReferenceDataCreateManyArgs>(args?: Prisma.SelectSubset<T, ReferenceDataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReferenceData and returns the data saved in the database.
   * @param {ReferenceDataCreateManyAndReturnArgs} args - Arguments to create many ReferenceData.
   * @example
   * // Create many ReferenceData
   * const referenceData = await prisma.referenceData.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReferenceData and only return the `id`
   * const referenceDataWithIdOnly = await prisma.referenceData.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReferenceDataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReferenceDataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReferenceData.
   * @param {ReferenceDataDeleteArgs} args - Arguments to delete one ReferenceData.
   * @example
   * // Delete one ReferenceData
   * const ReferenceData = await prisma.referenceData.delete({
   *   where: {
   *     // ... filter to delete one ReferenceData
   *   }
   * })
   * 
   */
  delete<T extends ReferenceDataDeleteArgs>(args: Prisma.SelectSubset<T, ReferenceDataDeleteArgs<ExtArgs>>): Prisma.Prisma__ReferenceDataClient<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReferenceData.
   * @param {ReferenceDataUpdateArgs} args - Arguments to update one ReferenceData.
   * @example
   * // Update one ReferenceData
   * const referenceData = await prisma.referenceData.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReferenceDataUpdateArgs>(args: Prisma.SelectSubset<T, ReferenceDataUpdateArgs<ExtArgs>>): Prisma.Prisma__ReferenceDataClient<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReferenceData.
   * @param {ReferenceDataDeleteManyArgs} args - Arguments to filter ReferenceData to delete.
   * @example
   * // Delete a few ReferenceData
   * const { count } = await prisma.referenceData.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReferenceDataDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReferenceDataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReferenceData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReferenceDataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReferenceData
   * const referenceData = await prisma.referenceData.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReferenceDataUpdateManyArgs>(args: Prisma.SelectSubset<T, ReferenceDataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReferenceData and returns the data updated in the database.
   * @param {ReferenceDataUpdateManyAndReturnArgs} args - Arguments to update many ReferenceData.
   * @example
   * // Update many ReferenceData
   * const referenceData = await prisma.referenceData.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReferenceData and only return the `id`
   * const referenceDataWithIdOnly = await prisma.referenceData.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReferenceDataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReferenceDataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReferenceData.
   * @param {ReferenceDataUpsertArgs} args - Arguments to update or create a ReferenceData.
   * @example
   * // Update or create a ReferenceData
   * const referenceData = await prisma.referenceData.upsert({
   *   create: {
   *     // ... data to create a ReferenceData
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReferenceData we want to update
   *   }
   * })
   */
  upsert<T extends ReferenceDataUpsertArgs>(args: Prisma.SelectSubset<T, ReferenceDataUpsertArgs<ExtArgs>>): Prisma.Prisma__ReferenceDataClient<runtime.Types.Result.GetResult<Prisma.$ReferenceDataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReferenceData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReferenceDataCountArgs} args - Arguments to filter ReferenceData to count.
   * @example
   * // Count the number of ReferenceData
   * const count = await prisma.referenceData.count({
   *   where: {
   *     // ... the filter for the ReferenceData we want to count
   *   }
   * })
  **/
  count<T extends ReferenceDataCountArgs>(
    args?: Prisma.Subset<T, ReferenceDataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReferenceDataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReferenceData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReferenceDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReferenceDataAggregateArgs>(args: Prisma.Subset<T, ReferenceDataAggregateArgs>): Prisma.PrismaPromise<GetReferenceDataAggregateType<T>>

  /**
   * Group by ReferenceData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReferenceDataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReferenceDataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReferenceDataGroupByArgs['orderBy'] }
      : { orderBy?: ReferenceDataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReferenceDataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReferenceDataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReferenceData model
 */
readonly fields: ReferenceDataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReferenceData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReferenceDataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReferenceData model
 */
export interface ReferenceDataFieldRefs {
  readonly id: Prisma.FieldRef<"ReferenceData", 'String'>
  readonly group: Prisma.FieldRef<"ReferenceData", 'String'>
  readonly key: Prisma.FieldRef<"ReferenceData", 'String'>
  readonly label: Prisma.FieldRef<"ReferenceData", 'String'>
  readonly order: Prisma.FieldRef<"ReferenceData", 'Int'>
  readonly isActive: Prisma.FieldRef<"ReferenceData", 'Boolean'>
}
    

// Custom InputTypes
/**
 * ReferenceData findUnique
 */
export type ReferenceDataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * Filter, which ReferenceData to fetch.
   */
  where: Prisma.ReferenceDataWhereUniqueInput
}

/**
 * ReferenceData findUniqueOrThrow
 */
export type ReferenceDataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * Filter, which ReferenceData to fetch.
   */
  where: Prisma.ReferenceDataWhereUniqueInput
}

/**
 * ReferenceData findFirst
 */
export type ReferenceDataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * Filter, which ReferenceData to fetch.
   */
  where?: Prisma.ReferenceDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReferenceData to fetch.
   */
  orderBy?: Prisma.ReferenceDataOrderByWithRelationInput | Prisma.ReferenceDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReferenceData.
   */
  cursor?: Prisma.ReferenceDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReferenceData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReferenceData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReferenceData.
   */
  distinct?: Prisma.ReferenceDataScalarFieldEnum | Prisma.ReferenceDataScalarFieldEnum[]
}

/**
 * ReferenceData findFirstOrThrow
 */
export type ReferenceDataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * Filter, which ReferenceData to fetch.
   */
  where?: Prisma.ReferenceDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReferenceData to fetch.
   */
  orderBy?: Prisma.ReferenceDataOrderByWithRelationInput | Prisma.ReferenceDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReferenceData.
   */
  cursor?: Prisma.ReferenceDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReferenceData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReferenceData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReferenceData.
   */
  distinct?: Prisma.ReferenceDataScalarFieldEnum | Prisma.ReferenceDataScalarFieldEnum[]
}

/**
 * ReferenceData findMany
 */
export type ReferenceDataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * Filter, which ReferenceData to fetch.
   */
  where?: Prisma.ReferenceDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReferenceData to fetch.
   */
  orderBy?: Prisma.ReferenceDataOrderByWithRelationInput | Prisma.ReferenceDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReferenceData.
   */
  cursor?: Prisma.ReferenceDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReferenceData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReferenceData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReferenceData.
   */
  distinct?: Prisma.ReferenceDataScalarFieldEnum | Prisma.ReferenceDataScalarFieldEnum[]
}

/**
 * ReferenceData create
 */
export type ReferenceDataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * The data needed to create a ReferenceData.
   */
  data: Prisma.XOR<Prisma.ReferenceDataCreateInput, Prisma.ReferenceDataUncheckedCreateInput>
}

/**
 * ReferenceData createMany
 */
export type ReferenceDataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReferenceData.
   */
  data: Prisma.ReferenceDataCreateManyInput | Prisma.ReferenceDataCreateManyInput[]
}

/**
 * ReferenceData createManyAndReturn
 */
export type ReferenceDataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * The data used to create many ReferenceData.
   */
  data: Prisma.ReferenceDataCreateManyInput | Prisma.ReferenceDataCreateManyInput[]
}

/**
 * ReferenceData update
 */
export type ReferenceDataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * The data needed to update a ReferenceData.
   */
  data: Prisma.XOR<Prisma.ReferenceDataUpdateInput, Prisma.ReferenceDataUncheckedUpdateInput>
  /**
   * Choose, which ReferenceData to update.
   */
  where: Prisma.ReferenceDataWhereUniqueInput
}

/**
 * ReferenceData updateMany
 */
export type ReferenceDataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReferenceData.
   */
  data: Prisma.XOR<Prisma.ReferenceDataUpdateManyMutationInput, Prisma.ReferenceDataUncheckedUpdateManyInput>
  /**
   * Filter which ReferenceData to update
   */
  where?: Prisma.ReferenceDataWhereInput
  /**
   * Limit how many ReferenceData to update.
   */
  limit?: number
}

/**
 * ReferenceData updateManyAndReturn
 */
export type ReferenceDataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * The data used to update ReferenceData.
   */
  data: Prisma.XOR<Prisma.ReferenceDataUpdateManyMutationInput, Prisma.ReferenceDataUncheckedUpdateManyInput>
  /**
   * Filter which ReferenceData to update
   */
  where?: Prisma.ReferenceDataWhereInput
  /**
   * Limit how many ReferenceData to update.
   */
  limit?: number
}

/**
 * ReferenceData upsert
 */
export type ReferenceDataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * The filter to search for the ReferenceData to update in case it exists.
   */
  where: Prisma.ReferenceDataWhereUniqueInput
  /**
   * In case the ReferenceData found by the `where` argument doesn't exist, create a new ReferenceData with this data.
   */
  create: Prisma.XOR<Prisma.ReferenceDataCreateInput, Prisma.ReferenceDataUncheckedCreateInput>
  /**
   * In case the ReferenceData was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReferenceDataUpdateInput, Prisma.ReferenceDataUncheckedUpdateInput>
}

/**
 * ReferenceData delete
 */
export type ReferenceDataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
  /**
   * Filter which ReferenceData to delete.
   */
  where: Prisma.ReferenceDataWhereUniqueInput
}

/**
 * ReferenceData deleteMany
 */
export type ReferenceDataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReferenceData to delete
   */
  where?: Prisma.ReferenceDataWhereInput
  /**
   * Limit how many ReferenceData to delete.
   */
  limit?: number
}

/**
 * ReferenceData without action
 */
export type ReferenceDataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferenceData
   */
  select?: Prisma.ReferenceDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferenceData
   */
  omit?: Prisma.ReferenceDataOmit<ExtArgs> | null
}
