
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Topic` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Topic
 * 
 */
export type TopicModel = runtime.Types.Result.DefaultSelection<Prisma.$TopicPayload>

export type AggregateTopic = {
  _count: TopicCountAggregateOutputType | null
  _avg: TopicAvgAggregateOutputType | null
  _sum: TopicSumAggregateOutputType | null
  _min: TopicMinAggregateOutputType | null
  _max: TopicMaxAggregateOutputType | null
}

export type TopicAvgAggregateOutputType = {
  views: number | null
}

export type TopicSumAggregateOutputType = {
  views: number | null
}

export type TopicMinAggregateOutputType = {
  id: string | null
  title: string | null
  isLocked: boolean | null
  isSticky: boolean | null
  isArchived: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  views: number | null
  forumId: string | null
  authorId: string | null
  tournamentId: string | null
}

export type TopicMaxAggregateOutputType = {
  id: string | null
  title: string | null
  isLocked: boolean | null
  isSticky: boolean | null
  isArchived: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  views: number | null
  forumId: string | null
  authorId: string | null
  tournamentId: string | null
}

export type TopicCountAggregateOutputType = {
  id: number
  title: number
  isLocked: number
  isSticky: number
  isArchived: number
  createdAt: number
  updatedAt: number
  views: number
  forumId: number
  authorId: number
  tournamentId: number
  _all: number
}


export type TopicAvgAggregateInputType = {
  views?: true
}

export type TopicSumAggregateInputType = {
  views?: true
}

export type TopicMinAggregateInputType = {
  id?: true
  title?: true
  isLocked?: true
  isSticky?: true
  isArchived?: true
  createdAt?: true
  updatedAt?: true
  views?: true
  forumId?: true
  authorId?: true
  tournamentId?: true
}

export type TopicMaxAggregateInputType = {
  id?: true
  title?: true
  isLocked?: true
  isSticky?: true
  isArchived?: true
  createdAt?: true
  updatedAt?: true
  views?: true
  forumId?: true
  authorId?: true
  tournamentId?: true
}

export type TopicCountAggregateInputType = {
  id?: true
  title?: true
  isLocked?: true
  isSticky?: true
  isArchived?: true
  createdAt?: true
  updatedAt?: true
  views?: true
  forumId?: true
  authorId?: true
  tournamentId?: true
  _all?: true
}

export type TopicAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Topic to aggregate.
   */
  where?: Prisma.TopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Topics to fetch.
   */
  orderBy?: Prisma.TopicOrderByWithRelationInput | Prisma.TopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Topics
  **/
  _count?: true | TopicCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TopicAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TopicSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TopicMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TopicMaxAggregateInputType
}

export type GetTopicAggregateType<T extends TopicAggregateArgs> = {
      [P in keyof T & keyof AggregateTopic]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTopic[P]>
    : Prisma.GetScalarType<T[P], AggregateTopic[P]>
}




export type TopicGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TopicWhereInput
  orderBy?: Prisma.TopicOrderByWithAggregationInput | Prisma.TopicOrderByWithAggregationInput[]
  by: Prisma.TopicScalarFieldEnum[] | Prisma.TopicScalarFieldEnum
  having?: Prisma.TopicScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TopicCountAggregateInputType | true
  _avg?: TopicAvgAggregateInputType
  _sum?: TopicSumAggregateInputType
  _min?: TopicMinAggregateInputType
  _max?: TopicMaxAggregateInputType
}

export type TopicGroupByOutputType = {
  id: string
  title: string
  isLocked: boolean
  isSticky: boolean
  isArchived: boolean
  createdAt: Date
  updatedAt: Date
  views: number
  forumId: string
  authorId: string
  tournamentId: string | null
  _count: TopicCountAggregateOutputType | null
  _avg: TopicAvgAggregateOutputType | null
  _sum: TopicSumAggregateOutputType | null
  _min: TopicMinAggregateOutputType | null
  _max: TopicMaxAggregateOutputType | null
}

type GetTopicGroupByPayload<T extends TopicGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TopicGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TopicGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TopicGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TopicGroupByOutputType[P]>
      }
    >
  >



export type TopicWhereInput = {
  AND?: Prisma.TopicWhereInput | Prisma.TopicWhereInput[]
  OR?: Prisma.TopicWhereInput[]
  NOT?: Prisma.TopicWhereInput | Prisma.TopicWhereInput[]
  id?: Prisma.StringFilter<"Topic"> | string
  title?: Prisma.StringFilter<"Topic"> | string
  isLocked?: Prisma.BoolFilter<"Topic"> | boolean
  isSticky?: Prisma.BoolFilter<"Topic"> | boolean
  isArchived?: Prisma.BoolFilter<"Topic"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  views?: Prisma.IntFilter<"Topic"> | number
  forumId?: Prisma.StringFilter<"Topic"> | string
  authorId?: Prisma.StringFilter<"Topic"> | string
  tournamentId?: Prisma.StringNullableFilter<"Topic"> | string | null
  posts?: Prisma.PostListRelationFilter
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  forum?: Prisma.XOR<Prisma.ForumScalarRelationFilter, Prisma.ForumWhereInput>
  follows?: Prisma.TopicFollowListRelationFilter
  topicViews?: Prisma.TopicViewListRelationFilter
}

export type TopicOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  isLocked?: Prisma.SortOrder
  isSticky?: Prisma.SortOrder
  isArchived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  views?: Prisma.SortOrder
  forumId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  posts?: Prisma.PostOrderByRelationAggregateInput
  tournament?: Prisma.TournamentOrderByWithRelationInput
  author?: Prisma.UserOrderByWithRelationInput
  forum?: Prisma.ForumOrderByWithRelationInput
  follows?: Prisma.TopicFollowOrderByRelationAggregateInput
  topicViews?: Prisma.TopicViewOrderByRelationAggregateInput
}

export type TopicWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  tournamentId?: string
  AND?: Prisma.TopicWhereInput | Prisma.TopicWhereInput[]
  OR?: Prisma.TopicWhereInput[]
  NOT?: Prisma.TopicWhereInput | Prisma.TopicWhereInput[]
  title?: Prisma.StringFilter<"Topic"> | string
  isLocked?: Prisma.BoolFilter<"Topic"> | boolean
  isSticky?: Prisma.BoolFilter<"Topic"> | boolean
  isArchived?: Prisma.BoolFilter<"Topic"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  views?: Prisma.IntFilter<"Topic"> | number
  forumId?: Prisma.StringFilter<"Topic"> | string
  authorId?: Prisma.StringFilter<"Topic"> | string
  posts?: Prisma.PostListRelationFilter
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  forum?: Prisma.XOR<Prisma.ForumScalarRelationFilter, Prisma.ForumWhereInput>
  follows?: Prisma.TopicFollowListRelationFilter
  topicViews?: Prisma.TopicViewListRelationFilter
}, "id" | "tournamentId">

export type TopicOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  isLocked?: Prisma.SortOrder
  isSticky?: Prisma.SortOrder
  isArchived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  views?: Prisma.SortOrder
  forumId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TopicCountOrderByAggregateInput
  _avg?: Prisma.TopicAvgOrderByAggregateInput
  _max?: Prisma.TopicMaxOrderByAggregateInput
  _min?: Prisma.TopicMinOrderByAggregateInput
  _sum?: Prisma.TopicSumOrderByAggregateInput
}

export type TopicScalarWhereWithAggregatesInput = {
  AND?: Prisma.TopicScalarWhereWithAggregatesInput | Prisma.TopicScalarWhereWithAggregatesInput[]
  OR?: Prisma.TopicScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TopicScalarWhereWithAggregatesInput | Prisma.TopicScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Topic"> | string
  title?: Prisma.StringWithAggregatesFilter<"Topic"> | string
  isLocked?: Prisma.BoolWithAggregatesFilter<"Topic"> | boolean
  isSticky?: Prisma.BoolWithAggregatesFilter<"Topic"> | boolean
  isArchived?: Prisma.BoolWithAggregatesFilter<"Topic"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Topic"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Topic"> | Date | string
  views?: Prisma.IntWithAggregatesFilter<"Topic"> | number
  forumId?: Prisma.StringWithAggregatesFilter<"Topic"> | string
  authorId?: Prisma.StringWithAggregatesFilter<"Topic"> | string
  tournamentId?: Prisma.StringNullableWithAggregatesFilter<"Topic"> | string | null
}

export type TopicCreateInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  posts?: Prisma.PostCreateNestedManyWithoutTopicInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutTopicInput
  author: Prisma.UserCreateNestedOneWithoutTopicsInput
  forum: Prisma.ForumCreateNestedOneWithoutTopicsInput
  follows?: Prisma.TopicFollowCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  forumId: string
  authorId: string
  tournamentId?: string | null
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutTopicInput
  follows?: Prisma.TopicFollowUncheckedCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  posts?: Prisma.PostUpdateManyWithoutTopicNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutTopicNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTopicsNestedInput
  forum?: Prisma.ForumUpdateOneRequiredWithoutTopicsNestedInput
  follows?: Prisma.TopicFollowUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  forumId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  posts?: Prisma.PostUncheckedUpdateManyWithoutTopicNestedInput
  follows?: Prisma.TopicFollowUncheckedUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicCreateManyInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  forumId: string
  authorId: string
  tournamentId?: string | null
}

export type TopicUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopicUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  forumId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TopicListRelationFilter = {
  every?: Prisma.TopicWhereInput
  some?: Prisma.TopicWhereInput
  none?: Prisma.TopicWhereInput
}

export type TopicOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TopicNullableScalarRelationFilter = {
  is?: Prisma.TopicWhereInput | null
  isNot?: Prisma.TopicWhereInput | null
}

export type TopicCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  isLocked?: Prisma.SortOrder
  isSticky?: Prisma.SortOrder
  isArchived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  views?: Prisma.SortOrder
  forumId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
}

export type TopicAvgOrderByAggregateInput = {
  views?: Prisma.SortOrder
}

export type TopicMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  isLocked?: Prisma.SortOrder
  isSticky?: Prisma.SortOrder
  isArchived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  views?: Prisma.SortOrder
  forumId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
}

export type TopicMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  isLocked?: Prisma.SortOrder
  isSticky?: Prisma.SortOrder
  isArchived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  views?: Prisma.SortOrder
  forumId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
}

export type TopicSumOrderByAggregateInput = {
  views?: Prisma.SortOrder
}

export type TopicScalarRelationFilter = {
  is?: Prisma.TopicWhereInput
  isNot?: Prisma.TopicWhereInput
}

export type TopicCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutAuthorInput, Prisma.TopicUncheckedCreateWithoutAuthorInput> | Prisma.TopicCreateWithoutAuthorInput[] | Prisma.TopicUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutAuthorInput | Prisma.TopicCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.TopicCreateManyAuthorInputEnvelope
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
}

export type TopicUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutAuthorInput, Prisma.TopicUncheckedCreateWithoutAuthorInput> | Prisma.TopicCreateWithoutAuthorInput[] | Prisma.TopicUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutAuthorInput | Prisma.TopicCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.TopicCreateManyAuthorInputEnvelope
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
}

export type TopicUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutAuthorInput, Prisma.TopicUncheckedCreateWithoutAuthorInput> | Prisma.TopicCreateWithoutAuthorInput[] | Prisma.TopicUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutAuthorInput | Prisma.TopicCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.TopicUpsertWithWhereUniqueWithoutAuthorInput | Prisma.TopicUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.TopicCreateManyAuthorInputEnvelope
  set?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  disconnect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  delete?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  update?: Prisma.TopicUpdateWithWhereUniqueWithoutAuthorInput | Prisma.TopicUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.TopicUpdateManyWithWhereWithoutAuthorInput | Prisma.TopicUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
}

export type TopicUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutAuthorInput, Prisma.TopicUncheckedCreateWithoutAuthorInput> | Prisma.TopicCreateWithoutAuthorInput[] | Prisma.TopicUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutAuthorInput | Prisma.TopicCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.TopicUpsertWithWhereUniqueWithoutAuthorInput | Prisma.TopicUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.TopicCreateManyAuthorInputEnvelope
  set?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  disconnect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  delete?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  update?: Prisma.TopicUpdateWithWhereUniqueWithoutAuthorInput | Prisma.TopicUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.TopicUpdateManyWithWhereWithoutAuthorInput | Prisma.TopicUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
}

export type TopicCreateNestedOneWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutTournamentInput, Prisma.TopicUncheckedCreateWithoutTournamentInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutTournamentInput
  connect?: Prisma.TopicWhereUniqueInput
}

export type TopicUncheckedCreateNestedOneWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutTournamentInput, Prisma.TopicUncheckedCreateWithoutTournamentInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutTournamentInput
  connect?: Prisma.TopicWhereUniqueInput
}

export type TopicUpdateOneWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutTournamentInput, Prisma.TopicUncheckedCreateWithoutTournamentInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutTournamentInput
  upsert?: Prisma.TopicUpsertWithoutTournamentInput
  disconnect?: Prisma.TopicWhereInput | boolean
  delete?: Prisma.TopicWhereInput | boolean
  connect?: Prisma.TopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TopicUpdateToOneWithWhereWithoutTournamentInput, Prisma.TopicUpdateWithoutTournamentInput>, Prisma.TopicUncheckedUpdateWithoutTournamentInput>
}

export type TopicUncheckedUpdateOneWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutTournamentInput, Prisma.TopicUncheckedCreateWithoutTournamentInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutTournamentInput
  upsert?: Prisma.TopicUpsertWithoutTournamentInput
  disconnect?: Prisma.TopicWhereInput | boolean
  delete?: Prisma.TopicWhereInput | boolean
  connect?: Prisma.TopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TopicUpdateToOneWithWhereWithoutTournamentInput, Prisma.TopicUpdateWithoutTournamentInput>, Prisma.TopicUncheckedUpdateWithoutTournamentInput>
}

export type TopicCreateNestedManyWithoutForumInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutForumInput, Prisma.TopicUncheckedCreateWithoutForumInput> | Prisma.TopicCreateWithoutForumInput[] | Prisma.TopicUncheckedCreateWithoutForumInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutForumInput | Prisma.TopicCreateOrConnectWithoutForumInput[]
  createMany?: Prisma.TopicCreateManyForumInputEnvelope
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
}

export type TopicUncheckedCreateNestedManyWithoutForumInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutForumInput, Prisma.TopicUncheckedCreateWithoutForumInput> | Prisma.TopicCreateWithoutForumInput[] | Prisma.TopicUncheckedCreateWithoutForumInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutForumInput | Prisma.TopicCreateOrConnectWithoutForumInput[]
  createMany?: Prisma.TopicCreateManyForumInputEnvelope
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
}

export type TopicUpdateManyWithoutForumNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutForumInput, Prisma.TopicUncheckedCreateWithoutForumInput> | Prisma.TopicCreateWithoutForumInput[] | Prisma.TopicUncheckedCreateWithoutForumInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutForumInput | Prisma.TopicCreateOrConnectWithoutForumInput[]
  upsert?: Prisma.TopicUpsertWithWhereUniqueWithoutForumInput | Prisma.TopicUpsertWithWhereUniqueWithoutForumInput[]
  createMany?: Prisma.TopicCreateManyForumInputEnvelope
  set?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  disconnect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  delete?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  update?: Prisma.TopicUpdateWithWhereUniqueWithoutForumInput | Prisma.TopicUpdateWithWhereUniqueWithoutForumInput[]
  updateMany?: Prisma.TopicUpdateManyWithWhereWithoutForumInput | Prisma.TopicUpdateManyWithWhereWithoutForumInput[]
  deleteMany?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
}

export type TopicUncheckedUpdateManyWithoutForumNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutForumInput, Prisma.TopicUncheckedCreateWithoutForumInput> | Prisma.TopicCreateWithoutForumInput[] | Prisma.TopicUncheckedCreateWithoutForumInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutForumInput | Prisma.TopicCreateOrConnectWithoutForumInput[]
  upsert?: Prisma.TopicUpsertWithWhereUniqueWithoutForumInput | Prisma.TopicUpsertWithWhereUniqueWithoutForumInput[]
  createMany?: Prisma.TopicCreateManyForumInputEnvelope
  set?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  disconnect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  delete?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  update?: Prisma.TopicUpdateWithWhereUniqueWithoutForumInput | Prisma.TopicUpdateWithWhereUniqueWithoutForumInput[]
  updateMany?: Prisma.TopicUpdateManyWithWhereWithoutForumInput | Prisma.TopicUpdateManyWithWhereWithoutForumInput[]
  deleteMany?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
}

export type TopicCreateNestedOneWithoutPostsInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutPostsInput, Prisma.TopicUncheckedCreateWithoutPostsInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutPostsInput
  connect?: Prisma.TopicWhereUniqueInput
}

export type TopicUpdateOneRequiredWithoutPostsNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutPostsInput, Prisma.TopicUncheckedCreateWithoutPostsInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutPostsInput
  upsert?: Prisma.TopicUpsertWithoutPostsInput
  connect?: Prisma.TopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TopicUpdateToOneWithWhereWithoutPostsInput, Prisma.TopicUpdateWithoutPostsInput>, Prisma.TopicUncheckedUpdateWithoutPostsInput>
}

export type TopicCreateNestedOneWithoutTopicViewsInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutTopicViewsInput, Prisma.TopicUncheckedCreateWithoutTopicViewsInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutTopicViewsInput
  connect?: Prisma.TopicWhereUniqueInput
}

export type TopicUpdateOneRequiredWithoutTopicViewsNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutTopicViewsInput, Prisma.TopicUncheckedCreateWithoutTopicViewsInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutTopicViewsInput
  upsert?: Prisma.TopicUpsertWithoutTopicViewsInput
  connect?: Prisma.TopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TopicUpdateToOneWithWhereWithoutTopicViewsInput, Prisma.TopicUpdateWithoutTopicViewsInput>, Prisma.TopicUncheckedUpdateWithoutTopicViewsInput>
}

export type TopicCreateNestedOneWithoutFollowsInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutFollowsInput, Prisma.TopicUncheckedCreateWithoutFollowsInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutFollowsInput
  connect?: Prisma.TopicWhereUniqueInput
}

export type TopicUpdateOneRequiredWithoutFollowsNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutFollowsInput, Prisma.TopicUncheckedCreateWithoutFollowsInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutFollowsInput
  upsert?: Prisma.TopicUpsertWithoutFollowsInput
  connect?: Prisma.TopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TopicUpdateToOneWithWhereWithoutFollowsInput, Prisma.TopicUpdateWithoutFollowsInput>, Prisma.TopicUncheckedUpdateWithoutFollowsInput>
}

export type TopicCreateWithoutAuthorInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  posts?: Prisma.PostCreateNestedManyWithoutTopicInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutTopicInput
  forum: Prisma.ForumCreateNestedOneWithoutTopicsInput
  follows?: Prisma.TopicFollowCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutAuthorInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  forumId: string
  tournamentId?: string | null
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutTopicInput
  follows?: Prisma.TopicFollowUncheckedCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutAuthorInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutAuthorInput, Prisma.TopicUncheckedCreateWithoutAuthorInput>
}

export type TopicCreateManyAuthorInputEnvelope = {
  data: Prisma.TopicCreateManyAuthorInput | Prisma.TopicCreateManyAuthorInput[]
}

export type TopicUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.TopicWhereUniqueInput
  update: Prisma.XOR<Prisma.TopicUpdateWithoutAuthorInput, Prisma.TopicUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutAuthorInput, Prisma.TopicUncheckedCreateWithoutAuthorInput>
}

export type TopicUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.TopicWhereUniqueInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutAuthorInput, Prisma.TopicUncheckedUpdateWithoutAuthorInput>
}

export type TopicUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.TopicScalarWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateManyMutationInput, Prisma.TopicUncheckedUpdateManyWithoutAuthorInput>
}

export type TopicScalarWhereInput = {
  AND?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
  OR?: Prisma.TopicScalarWhereInput[]
  NOT?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
  id?: Prisma.StringFilter<"Topic"> | string
  title?: Prisma.StringFilter<"Topic"> | string
  isLocked?: Prisma.BoolFilter<"Topic"> | boolean
  isSticky?: Prisma.BoolFilter<"Topic"> | boolean
  isArchived?: Prisma.BoolFilter<"Topic"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  views?: Prisma.IntFilter<"Topic"> | number
  forumId?: Prisma.StringFilter<"Topic"> | string
  authorId?: Prisma.StringFilter<"Topic"> | string
  tournamentId?: Prisma.StringNullableFilter<"Topic"> | string | null
}

export type TopicCreateWithoutTournamentInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  posts?: Prisma.PostCreateNestedManyWithoutTopicInput
  author: Prisma.UserCreateNestedOneWithoutTopicsInput
  forum: Prisma.ForumCreateNestedOneWithoutTopicsInput
  follows?: Prisma.TopicFollowCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutTournamentInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  forumId: string
  authorId: string
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutTopicInput
  follows?: Prisma.TopicFollowUncheckedCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutTournamentInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutTournamentInput, Prisma.TopicUncheckedCreateWithoutTournamentInput>
}

export type TopicUpsertWithoutTournamentInput = {
  update: Prisma.XOR<Prisma.TopicUpdateWithoutTournamentInput, Prisma.TopicUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutTournamentInput, Prisma.TopicUncheckedCreateWithoutTournamentInput>
  where?: Prisma.TopicWhereInput
}

export type TopicUpdateToOneWithWhereWithoutTournamentInput = {
  where?: Prisma.TopicWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutTournamentInput, Prisma.TopicUncheckedUpdateWithoutTournamentInput>
}

export type TopicUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  posts?: Prisma.PostUpdateManyWithoutTopicNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTopicsNestedInput
  forum?: Prisma.ForumUpdateOneRequiredWithoutTopicsNestedInput
  follows?: Prisma.TopicFollowUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  forumId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  posts?: Prisma.PostUncheckedUpdateManyWithoutTopicNestedInput
  follows?: Prisma.TopicFollowUncheckedUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicCreateWithoutForumInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  posts?: Prisma.PostCreateNestedManyWithoutTopicInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutTopicInput
  author: Prisma.UserCreateNestedOneWithoutTopicsInput
  follows?: Prisma.TopicFollowCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutForumInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  authorId: string
  tournamentId?: string | null
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutTopicInput
  follows?: Prisma.TopicFollowUncheckedCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutForumInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutForumInput, Prisma.TopicUncheckedCreateWithoutForumInput>
}

export type TopicCreateManyForumInputEnvelope = {
  data: Prisma.TopicCreateManyForumInput | Prisma.TopicCreateManyForumInput[]
}

export type TopicUpsertWithWhereUniqueWithoutForumInput = {
  where: Prisma.TopicWhereUniqueInput
  update: Prisma.XOR<Prisma.TopicUpdateWithoutForumInput, Prisma.TopicUncheckedUpdateWithoutForumInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutForumInput, Prisma.TopicUncheckedCreateWithoutForumInput>
}

export type TopicUpdateWithWhereUniqueWithoutForumInput = {
  where: Prisma.TopicWhereUniqueInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutForumInput, Prisma.TopicUncheckedUpdateWithoutForumInput>
}

export type TopicUpdateManyWithWhereWithoutForumInput = {
  where: Prisma.TopicScalarWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateManyMutationInput, Prisma.TopicUncheckedUpdateManyWithoutForumInput>
}

export type TopicCreateWithoutPostsInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  tournament?: Prisma.TournamentCreateNestedOneWithoutTopicInput
  author: Prisma.UserCreateNestedOneWithoutTopicsInput
  forum: Prisma.ForumCreateNestedOneWithoutTopicsInput
  follows?: Prisma.TopicFollowCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutPostsInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  forumId: string
  authorId: string
  tournamentId?: string | null
  follows?: Prisma.TopicFollowUncheckedCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutPostsInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutPostsInput, Prisma.TopicUncheckedCreateWithoutPostsInput>
}

export type TopicUpsertWithoutPostsInput = {
  update: Prisma.XOR<Prisma.TopicUpdateWithoutPostsInput, Prisma.TopicUncheckedUpdateWithoutPostsInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutPostsInput, Prisma.TopicUncheckedCreateWithoutPostsInput>
  where?: Prisma.TopicWhereInput
}

export type TopicUpdateToOneWithWhereWithoutPostsInput = {
  where?: Prisma.TopicWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutPostsInput, Prisma.TopicUncheckedUpdateWithoutPostsInput>
}

export type TopicUpdateWithoutPostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  tournament?: Prisma.TournamentUpdateOneWithoutTopicNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTopicsNestedInput
  forum?: Prisma.ForumUpdateOneRequiredWithoutTopicsNestedInput
  follows?: Prisma.TopicFollowUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutPostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  forumId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  follows?: Prisma.TopicFollowUncheckedUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicCreateWithoutTopicViewsInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  posts?: Prisma.PostCreateNestedManyWithoutTopicInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutTopicInput
  author: Prisma.UserCreateNestedOneWithoutTopicsInput
  forum: Prisma.ForumCreateNestedOneWithoutTopicsInput
  follows?: Prisma.TopicFollowCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutTopicViewsInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  forumId: string
  authorId: string
  tournamentId?: string | null
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutTopicInput
  follows?: Prisma.TopicFollowUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutTopicViewsInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutTopicViewsInput, Prisma.TopicUncheckedCreateWithoutTopicViewsInput>
}

export type TopicUpsertWithoutTopicViewsInput = {
  update: Prisma.XOR<Prisma.TopicUpdateWithoutTopicViewsInput, Prisma.TopicUncheckedUpdateWithoutTopicViewsInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutTopicViewsInput, Prisma.TopicUncheckedCreateWithoutTopicViewsInput>
  where?: Prisma.TopicWhereInput
}

export type TopicUpdateToOneWithWhereWithoutTopicViewsInput = {
  where?: Prisma.TopicWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutTopicViewsInput, Prisma.TopicUncheckedUpdateWithoutTopicViewsInput>
}

export type TopicUpdateWithoutTopicViewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  posts?: Prisma.PostUpdateManyWithoutTopicNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutTopicNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTopicsNestedInput
  forum?: Prisma.ForumUpdateOneRequiredWithoutTopicsNestedInput
  follows?: Prisma.TopicFollowUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutTopicViewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  forumId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  posts?: Prisma.PostUncheckedUpdateManyWithoutTopicNestedInput
  follows?: Prisma.TopicFollowUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicCreateWithoutFollowsInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  posts?: Prisma.PostCreateNestedManyWithoutTopicInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutTopicInput
  author: Prisma.UserCreateNestedOneWithoutTopicsInput
  forum: Prisma.ForumCreateNestedOneWithoutTopicsInput
  topicViews?: Prisma.TopicViewCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutFollowsInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  forumId: string
  authorId: string
  tournamentId?: string | null
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutTopicInput
  topicViews?: Prisma.TopicViewUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutFollowsInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutFollowsInput, Prisma.TopicUncheckedCreateWithoutFollowsInput>
}

export type TopicUpsertWithoutFollowsInput = {
  update: Prisma.XOR<Prisma.TopicUpdateWithoutFollowsInput, Prisma.TopicUncheckedUpdateWithoutFollowsInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutFollowsInput, Prisma.TopicUncheckedCreateWithoutFollowsInput>
  where?: Prisma.TopicWhereInput
}

export type TopicUpdateToOneWithWhereWithoutFollowsInput = {
  where?: Prisma.TopicWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutFollowsInput, Prisma.TopicUncheckedUpdateWithoutFollowsInput>
}

export type TopicUpdateWithoutFollowsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  posts?: Prisma.PostUpdateManyWithoutTopicNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutTopicNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTopicsNestedInput
  forum?: Prisma.ForumUpdateOneRequiredWithoutTopicsNestedInput
  topicViews?: Prisma.TopicViewUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutFollowsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  forumId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  posts?: Prisma.PostUncheckedUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicCreateManyAuthorInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  forumId: string
  tournamentId?: string | null
}

export type TopicUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  posts?: Prisma.PostUpdateManyWithoutTopicNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutTopicNestedInput
  forum?: Prisma.ForumUpdateOneRequiredWithoutTopicsNestedInput
  follows?: Prisma.TopicFollowUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  forumId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  posts?: Prisma.PostUncheckedUpdateManyWithoutTopicNestedInput
  follows?: Prisma.TopicFollowUncheckedUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  forumId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TopicCreateManyForumInput = {
  id?: string
  title: string
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  views?: number
  authorId: string
  tournamentId?: string | null
}

export type TopicUpdateWithoutForumInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  posts?: Prisma.PostUpdateManyWithoutTopicNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutTopicNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTopicsNestedInput
  follows?: Prisma.TopicFollowUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutForumInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  posts?: Prisma.PostUncheckedUpdateManyWithoutTopicNestedInput
  follows?: Prisma.TopicFollowUncheckedUpdateManyWithoutTopicNestedInput
  topicViews?: Prisma.TopicViewUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateManyWithoutForumInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  isLocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSticky?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isArchived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.IntFieldUpdateOperationsInput | number
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type TopicCountOutputType
 */

export type TopicCountOutputType = {
  posts: number
  follows: number
  topicViews: number
}

export type TopicCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  posts?: boolean | TopicCountOutputTypeCountPostsArgs
  follows?: boolean | TopicCountOutputTypeCountFollowsArgs
  topicViews?: boolean | TopicCountOutputTypeCountTopicViewsArgs
}

/**
 * TopicCountOutputType without action
 */
export type TopicCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicCountOutputType
   */
  select?: Prisma.TopicCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TopicCountOutputType without action
 */
export type TopicCountOutputTypeCountPostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostWhereInput
}

/**
 * TopicCountOutputType without action
 */
export type TopicCountOutputTypeCountFollowsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TopicFollowWhereInput
}

/**
 * TopicCountOutputType without action
 */
export type TopicCountOutputTypeCountTopicViewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TopicViewWhereInput
}


export type TopicSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  views?: boolean
  forumId?: boolean
  authorId?: boolean
  tournamentId?: boolean
  posts?: boolean | Prisma.Topic$postsArgs<ExtArgs>
  tournament?: boolean | Prisma.Topic$tournamentArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  forum?: boolean | Prisma.ForumDefaultArgs<ExtArgs>
  follows?: boolean | Prisma.Topic$followsArgs<ExtArgs>
  topicViews?: boolean | Prisma.Topic$topicViewsArgs<ExtArgs>
  _count?: boolean | Prisma.TopicCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topic"]>

export type TopicSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  views?: boolean
  forumId?: boolean
  authorId?: boolean
  tournamentId?: boolean
  tournament?: boolean | Prisma.Topic$tournamentArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  forum?: boolean | Prisma.ForumDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topic"]>

export type TopicSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  views?: boolean
  forumId?: boolean
  authorId?: boolean
  tournamentId?: boolean
  tournament?: boolean | Prisma.Topic$tournamentArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  forum?: boolean | Prisma.ForumDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topic"]>

export type TopicSelectScalar = {
  id?: boolean
  title?: boolean
  isLocked?: boolean
  isSticky?: boolean
  isArchived?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  views?: boolean
  forumId?: boolean
  authorId?: boolean
  tournamentId?: boolean
}

export type TopicOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "isLocked" | "isSticky" | "isArchived" | "createdAt" | "updatedAt" | "views" | "forumId" | "authorId" | "tournamentId", ExtArgs["result"]["topic"]>
export type TopicInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  posts?: boolean | Prisma.Topic$postsArgs<ExtArgs>
  tournament?: boolean | Prisma.Topic$tournamentArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  forum?: boolean | Prisma.ForumDefaultArgs<ExtArgs>
  follows?: boolean | Prisma.Topic$followsArgs<ExtArgs>
  topicViews?: boolean | Prisma.Topic$topicViewsArgs<ExtArgs>
  _count?: boolean | Prisma.TopicCountOutputTypeDefaultArgs<ExtArgs>
}
export type TopicIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.Topic$tournamentArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  forum?: boolean | Prisma.ForumDefaultArgs<ExtArgs>
}
export type TopicIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.Topic$tournamentArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  forum?: boolean | Prisma.ForumDefaultArgs<ExtArgs>
}

export type $TopicPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Topic"
  objects: {
    posts: Prisma.$PostPayload<ExtArgs>[]
    tournament: Prisma.$TournamentPayload<ExtArgs> | null
    author: Prisma.$UserPayload<ExtArgs>
    forum: Prisma.$ForumPayload<ExtArgs>
    follows: Prisma.$TopicFollowPayload<ExtArgs>[]
    topicViews: Prisma.$TopicViewPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    isLocked: boolean
    isSticky: boolean
    isArchived: boolean
    createdAt: Date
    updatedAt: Date
    views: number
    forumId: string
    authorId: string
    tournamentId: string | null
  }, ExtArgs["result"]["topic"]>
  composites: {}
}

export type TopicGetPayload<S extends boolean | null | undefined | TopicDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TopicPayload, S>

export type TopicCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TopicFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TopicCountAggregateInputType | true
  }

export interface TopicDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Topic'], meta: { name: 'Topic' } }
  /**
   * Find zero or one Topic that matches the filter.
   * @param {TopicFindUniqueArgs} args - Arguments to find a Topic
   * @example
   * // Get one Topic
   * const topic = await prisma.topic.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TopicFindUniqueArgs>(args: Prisma.SelectSubset<T, TopicFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Topic that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TopicFindUniqueOrThrowArgs} args - Arguments to find a Topic
   * @example
   * // Get one Topic
   * const topic = await prisma.topic.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TopicFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TopicFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Topic that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicFindFirstArgs} args - Arguments to find a Topic
   * @example
   * // Get one Topic
   * const topic = await prisma.topic.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TopicFindFirstArgs>(args?: Prisma.SelectSubset<T, TopicFindFirstArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Topic that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicFindFirstOrThrowArgs} args - Arguments to find a Topic
   * @example
   * // Get one Topic
   * const topic = await prisma.topic.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TopicFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TopicFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Topics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Topics
   * const topics = await prisma.topic.findMany()
   * 
   * // Get first 10 Topics
   * const topics = await prisma.topic.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const topicWithIdOnly = await prisma.topic.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TopicFindManyArgs>(args?: Prisma.SelectSubset<T, TopicFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Topic.
   * @param {TopicCreateArgs} args - Arguments to create a Topic.
   * @example
   * // Create one Topic
   * const Topic = await prisma.topic.create({
   *   data: {
   *     // ... data to create a Topic
   *   }
   * })
   * 
   */
  create<T extends TopicCreateArgs>(args: Prisma.SelectSubset<T, TopicCreateArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Topics.
   * @param {TopicCreateManyArgs} args - Arguments to create many Topics.
   * @example
   * // Create many Topics
   * const topic = await prisma.topic.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TopicCreateManyArgs>(args?: Prisma.SelectSubset<T, TopicCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Topics and returns the data saved in the database.
   * @param {TopicCreateManyAndReturnArgs} args - Arguments to create many Topics.
   * @example
   * // Create many Topics
   * const topic = await prisma.topic.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Topics and only return the `id`
   * const topicWithIdOnly = await prisma.topic.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TopicCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TopicCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Topic.
   * @param {TopicDeleteArgs} args - Arguments to delete one Topic.
   * @example
   * // Delete one Topic
   * const Topic = await prisma.topic.delete({
   *   where: {
   *     // ... filter to delete one Topic
   *   }
   * })
   * 
   */
  delete<T extends TopicDeleteArgs>(args: Prisma.SelectSubset<T, TopicDeleteArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Topic.
   * @param {TopicUpdateArgs} args - Arguments to update one Topic.
   * @example
   * // Update one Topic
   * const topic = await prisma.topic.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TopicUpdateArgs>(args: Prisma.SelectSubset<T, TopicUpdateArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Topics.
   * @param {TopicDeleteManyArgs} args - Arguments to filter Topics to delete.
   * @example
   * // Delete a few Topics
   * const { count } = await prisma.topic.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TopicDeleteManyArgs>(args?: Prisma.SelectSubset<T, TopicDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Topics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Topics
   * const topic = await prisma.topic.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TopicUpdateManyArgs>(args: Prisma.SelectSubset<T, TopicUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Topics and returns the data updated in the database.
   * @param {TopicUpdateManyAndReturnArgs} args - Arguments to update many Topics.
   * @example
   * // Update many Topics
   * const topic = await prisma.topic.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Topics and only return the `id`
   * const topicWithIdOnly = await prisma.topic.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TopicUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TopicUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Topic.
   * @param {TopicUpsertArgs} args - Arguments to update or create a Topic.
   * @example
   * // Update or create a Topic
   * const topic = await prisma.topic.upsert({
   *   create: {
   *     // ... data to create a Topic
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Topic we want to update
   *   }
   * })
   */
  upsert<T extends TopicUpsertArgs>(args: Prisma.SelectSubset<T, TopicUpsertArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Topics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicCountArgs} args - Arguments to filter Topics to count.
   * @example
   * // Count the number of Topics
   * const count = await prisma.topic.count({
   *   where: {
   *     // ... the filter for the Topics we want to count
   *   }
   * })
  **/
  count<T extends TopicCountArgs>(
    args?: Prisma.Subset<T, TopicCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TopicCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Topic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TopicAggregateArgs>(args: Prisma.Subset<T, TopicAggregateArgs>): Prisma.PrismaPromise<GetTopicAggregateType<T>>

  /**
   * Group by Topic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TopicGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TopicGroupByArgs['orderBy'] }
      : { orderBy?: TopicGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TopicGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTopicGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Topic model
 */
readonly fields: TopicFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Topic.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TopicClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  posts<T extends Prisma.Topic$postsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Topic$postsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tournament<T extends Prisma.Topic$tournamentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Topic$tournamentArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  author<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  forum<T extends Prisma.ForumDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumDefaultArgs<ExtArgs>>): Prisma.Prisma__ForumClient<runtime.Types.Result.GetResult<Prisma.$ForumPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  follows<T extends Prisma.Topic$followsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Topic$followsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicFollowPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  topicViews<T extends Prisma.Topic$topicViewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Topic$topicViewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicViewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Topic model
 */
export interface TopicFieldRefs {
  readonly id: Prisma.FieldRef<"Topic", 'String'>
  readonly title: Prisma.FieldRef<"Topic", 'String'>
  readonly isLocked: Prisma.FieldRef<"Topic", 'Boolean'>
  readonly isSticky: Prisma.FieldRef<"Topic", 'Boolean'>
  readonly isArchived: Prisma.FieldRef<"Topic", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Topic", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Topic", 'DateTime'>
  readonly views: Prisma.FieldRef<"Topic", 'Int'>
  readonly forumId: Prisma.FieldRef<"Topic", 'String'>
  readonly authorId: Prisma.FieldRef<"Topic", 'String'>
  readonly tournamentId: Prisma.FieldRef<"Topic", 'String'>
}
    

// Custom InputTypes
/**
 * Topic findUnique
 */
export type TopicFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topic to fetch.
   */
  where: Prisma.TopicWhereUniqueInput
}

/**
 * Topic findUniqueOrThrow
 */
export type TopicFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topic to fetch.
   */
  where: Prisma.TopicWhereUniqueInput
}

/**
 * Topic findFirst
 */
export type TopicFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topic to fetch.
   */
  where?: Prisma.TopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Topics to fetch.
   */
  orderBy?: Prisma.TopicOrderByWithRelationInput | Prisma.TopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Topics.
   */
  cursor?: Prisma.TopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Topics.
   */
  distinct?: Prisma.TopicScalarFieldEnum | Prisma.TopicScalarFieldEnum[]
}

/**
 * Topic findFirstOrThrow
 */
export type TopicFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topic to fetch.
   */
  where?: Prisma.TopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Topics to fetch.
   */
  orderBy?: Prisma.TopicOrderByWithRelationInput | Prisma.TopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Topics.
   */
  cursor?: Prisma.TopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Topics.
   */
  distinct?: Prisma.TopicScalarFieldEnum | Prisma.TopicScalarFieldEnum[]
}

/**
 * Topic findMany
 */
export type TopicFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topics to fetch.
   */
  where?: Prisma.TopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Topics to fetch.
   */
  orderBy?: Prisma.TopicOrderByWithRelationInput | Prisma.TopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Topics.
   */
  cursor?: Prisma.TopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Topics.
   */
  distinct?: Prisma.TopicScalarFieldEnum | Prisma.TopicScalarFieldEnum[]
}

/**
 * Topic create
 */
export type TopicCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * The data needed to create a Topic.
   */
  data: Prisma.XOR<Prisma.TopicCreateInput, Prisma.TopicUncheckedCreateInput>
}

/**
 * Topic createMany
 */
export type TopicCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Topics.
   */
  data: Prisma.TopicCreateManyInput | Prisma.TopicCreateManyInput[]
}

/**
 * Topic createManyAndReturn
 */
export type TopicCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * The data used to create many Topics.
   */
  data: Prisma.TopicCreateManyInput | Prisma.TopicCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Topic update
 */
export type TopicUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * The data needed to update a Topic.
   */
  data: Prisma.XOR<Prisma.TopicUpdateInput, Prisma.TopicUncheckedUpdateInput>
  /**
   * Choose, which Topic to update.
   */
  where: Prisma.TopicWhereUniqueInput
}

/**
 * Topic updateMany
 */
export type TopicUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Topics.
   */
  data: Prisma.XOR<Prisma.TopicUpdateManyMutationInput, Prisma.TopicUncheckedUpdateManyInput>
  /**
   * Filter which Topics to update
   */
  where?: Prisma.TopicWhereInput
  /**
   * Limit how many Topics to update.
   */
  limit?: number
}

/**
 * Topic updateManyAndReturn
 */
export type TopicUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * The data used to update Topics.
   */
  data: Prisma.XOR<Prisma.TopicUpdateManyMutationInput, Prisma.TopicUncheckedUpdateManyInput>
  /**
   * Filter which Topics to update
   */
  where?: Prisma.TopicWhereInput
  /**
   * Limit how many Topics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Topic upsert
 */
export type TopicUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * The filter to search for the Topic to update in case it exists.
   */
  where: Prisma.TopicWhereUniqueInput
  /**
   * In case the Topic found by the `where` argument doesn't exist, create a new Topic with this data.
   */
  create: Prisma.XOR<Prisma.TopicCreateInput, Prisma.TopicUncheckedCreateInput>
  /**
   * In case the Topic was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TopicUpdateInput, Prisma.TopicUncheckedUpdateInput>
}

/**
 * Topic delete
 */
export type TopicDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter which Topic to delete.
   */
  where: Prisma.TopicWhereUniqueInput
}

/**
 * Topic deleteMany
 */
export type TopicDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Topics to delete
   */
  where?: Prisma.TopicWhereInput
  /**
   * Limit how many Topics to delete.
   */
  limit?: number
}

/**
 * Topic.posts
 */
export type Topic$postsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Post
   */
  select?: Prisma.PostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Post
   */
  omit?: Prisma.PostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostInclude<ExtArgs> | null
  where?: Prisma.PostWhereInput
  orderBy?: Prisma.PostOrderByWithRelationInput | Prisma.PostOrderByWithRelationInput[]
  cursor?: Prisma.PostWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * Topic.tournament
 */
export type Topic$tournamentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  where?: Prisma.TournamentWhereInput
}

/**
 * Topic.follows
 */
export type Topic$followsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicFollow
   */
  select?: Prisma.TopicFollowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicFollow
   */
  omit?: Prisma.TopicFollowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicFollowInclude<ExtArgs> | null
  where?: Prisma.TopicFollowWhereInput
  orderBy?: Prisma.TopicFollowOrderByWithRelationInput | Prisma.TopicFollowOrderByWithRelationInput[]
  cursor?: Prisma.TopicFollowWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TopicFollowScalarFieldEnum | Prisma.TopicFollowScalarFieldEnum[]
}

/**
 * Topic.topicViews
 */
export type Topic$topicViewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicView
   */
  select?: Prisma.TopicViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicView
   */
  omit?: Prisma.TopicViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicViewInclude<ExtArgs> | null
  where?: Prisma.TopicViewWhereInput
  orderBy?: Prisma.TopicViewOrderByWithRelationInput | Prisma.TopicViewOrderByWithRelationInput[]
  cursor?: Prisma.TopicViewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TopicViewScalarFieldEnum | Prisma.TopicViewScalarFieldEnum[]
}

/**
 * Topic without action
 */
export type TopicDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
}
