
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TournamentResult` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TournamentResult
 * 
 */
export type TournamentResultModel = runtime.Types.Result.DefaultSelection<Prisma.$TournamentResultPayload>

export type AggregateTournamentResult = {
  _count: TournamentResultCountAggregateOutputType | null
  _avg: TournamentResultAvgAggregateOutputType | null
  _sum: TournamentResultSumAggregateOutputType | null
  _min: TournamentResultMinAggregateOutputType | null
  _max: TournamentResultMaxAggregateOutputType | null
}

export type TournamentResultAvgAggregateOutputType = {
  wins: number | null
  draws: number | null
  losses: number | null
  casualties: number | null
  points: number | null
  rank: number | null
}

export type TournamentResultSumAggregateOutputType = {
  wins: number | null
  draws: number | null
  losses: number | null
  casualties: number | null
  points: number | null
  rank: number | null
}

export type TournamentResultMinAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  coachName: string | null
  nafNumber: string | null
  userId: string | null
  roster: string | null
  wins: number | null
  draws: number | null
  losses: number | null
  casualties: number | null
  points: number | null
  rank: number | null
  autoCalculate: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TournamentResultMaxAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  coachName: string | null
  nafNumber: string | null
  userId: string | null
  roster: string | null
  wins: number | null
  draws: number | null
  losses: number | null
  casualties: number | null
  points: number | null
  rank: number | null
  autoCalculate: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TournamentResultCountAggregateOutputType = {
  id: number
  tournamentId: number
  coachName: number
  nafNumber: number
  userId: number
  roster: number
  wins: number
  draws: number
  losses: number
  casualties: number
  points: number
  rank: number
  autoCalculate: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TournamentResultAvgAggregateInputType = {
  wins?: true
  draws?: true
  losses?: true
  casualties?: true
  points?: true
  rank?: true
}

export type TournamentResultSumAggregateInputType = {
  wins?: true
  draws?: true
  losses?: true
  casualties?: true
  points?: true
  rank?: true
}

export type TournamentResultMinAggregateInputType = {
  id?: true
  tournamentId?: true
  coachName?: true
  nafNumber?: true
  userId?: true
  roster?: true
  wins?: true
  draws?: true
  losses?: true
  casualties?: true
  points?: true
  rank?: true
  autoCalculate?: true
  createdAt?: true
  updatedAt?: true
}

export type TournamentResultMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  coachName?: true
  nafNumber?: true
  userId?: true
  roster?: true
  wins?: true
  draws?: true
  losses?: true
  casualties?: true
  points?: true
  rank?: true
  autoCalculate?: true
  createdAt?: true
  updatedAt?: true
}

export type TournamentResultCountAggregateInputType = {
  id?: true
  tournamentId?: true
  coachName?: true
  nafNumber?: true
  userId?: true
  roster?: true
  wins?: true
  draws?: true
  losses?: true
  casualties?: true
  points?: true
  rank?: true
  autoCalculate?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TournamentResultAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentResult to aggregate.
   */
  where?: Prisma.TournamentResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentResults to fetch.
   */
  orderBy?: Prisma.TournamentResultOrderByWithRelationInput | Prisma.TournamentResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TournamentResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TournamentResults
  **/
  _count?: true | TournamentResultCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TournamentResultAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TournamentResultSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TournamentResultMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TournamentResultMaxAggregateInputType
}

export type GetTournamentResultAggregateType<T extends TournamentResultAggregateArgs> = {
      [P in keyof T & keyof AggregateTournamentResult]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTournamentResult[P]>
    : Prisma.GetScalarType<T[P], AggregateTournamentResult[P]>
}




export type TournamentResultGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TournamentResultWhereInput
  orderBy?: Prisma.TournamentResultOrderByWithAggregationInput | Prisma.TournamentResultOrderByWithAggregationInput[]
  by: Prisma.TournamentResultScalarFieldEnum[] | Prisma.TournamentResultScalarFieldEnum
  having?: Prisma.TournamentResultScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TournamentResultCountAggregateInputType | true
  _avg?: TournamentResultAvgAggregateInputType
  _sum?: TournamentResultSumAggregateInputType
  _min?: TournamentResultMinAggregateInputType
  _max?: TournamentResultMaxAggregateInputType
}

export type TournamentResultGroupByOutputType = {
  id: string
  tournamentId: string
  coachName: string
  nafNumber: string | null
  userId: string | null
  roster: string | null
  wins: number
  draws: number
  losses: number
  casualties: number
  points: number
  rank: number | null
  autoCalculate: boolean
  createdAt: Date
  updatedAt: Date
  _count: TournamentResultCountAggregateOutputType | null
  _avg: TournamentResultAvgAggregateOutputType | null
  _sum: TournamentResultSumAggregateOutputType | null
  _min: TournamentResultMinAggregateOutputType | null
  _max: TournamentResultMaxAggregateOutputType | null
}

type GetTournamentResultGroupByPayload<T extends TournamentResultGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TournamentResultGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TournamentResultGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TournamentResultGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TournamentResultGroupByOutputType[P]>
      }
    >
  >



export type TournamentResultWhereInput = {
  AND?: Prisma.TournamentResultWhereInput | Prisma.TournamentResultWhereInput[]
  OR?: Prisma.TournamentResultWhereInput[]
  NOT?: Prisma.TournamentResultWhereInput | Prisma.TournamentResultWhereInput[]
  id?: Prisma.StringFilter<"TournamentResult"> | string
  tournamentId?: Prisma.StringFilter<"TournamentResult"> | string
  coachName?: Prisma.StringFilter<"TournamentResult"> | string
  nafNumber?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  userId?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  roster?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  wins?: Prisma.IntFilter<"TournamentResult"> | number
  draws?: Prisma.IntFilter<"TournamentResult"> | number
  losses?: Prisma.IntFilter<"TournamentResult"> | number
  casualties?: Prisma.IntFilter<"TournamentResult"> | number
  points?: Prisma.FloatFilter<"TournamentResult"> | number
  rank?: Prisma.IntNullableFilter<"TournamentResult"> | number | null
  autoCalculate?: Prisma.BoolFilter<"TournamentResult"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TournamentResult"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentResult"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
}

export type TournamentResultOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  coachName?: Prisma.SortOrder
  nafNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  roster?: Prisma.SortOrderInput | Prisma.SortOrder
  wins?: Prisma.SortOrder
  draws?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  casualties?: Prisma.SortOrder
  points?: Prisma.SortOrder
  rank?: Prisma.SortOrderInput | Prisma.SortOrder
  autoCalculate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  tournament?: Prisma.TournamentOrderByWithRelationInput
}

export type TournamentResultWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  tournamentId_coachName?: Prisma.TournamentResultTournamentIdCoachNameCompoundUniqueInput
  AND?: Prisma.TournamentResultWhereInput | Prisma.TournamentResultWhereInput[]
  OR?: Prisma.TournamentResultWhereInput[]
  NOT?: Prisma.TournamentResultWhereInput | Prisma.TournamentResultWhereInput[]
  tournamentId?: Prisma.StringFilter<"TournamentResult"> | string
  coachName?: Prisma.StringFilter<"TournamentResult"> | string
  nafNumber?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  userId?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  roster?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  wins?: Prisma.IntFilter<"TournamentResult"> | number
  draws?: Prisma.IntFilter<"TournamentResult"> | number
  losses?: Prisma.IntFilter<"TournamentResult"> | number
  casualties?: Prisma.IntFilter<"TournamentResult"> | number
  points?: Prisma.FloatFilter<"TournamentResult"> | number
  rank?: Prisma.IntNullableFilter<"TournamentResult"> | number | null
  autoCalculate?: Prisma.BoolFilter<"TournamentResult"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TournamentResult"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentResult"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
}, "id" | "tournamentId_coachName">

export type TournamentResultOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  coachName?: Prisma.SortOrder
  nafNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  roster?: Prisma.SortOrderInput | Prisma.SortOrder
  wins?: Prisma.SortOrder
  draws?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  casualties?: Prisma.SortOrder
  points?: Prisma.SortOrder
  rank?: Prisma.SortOrderInput | Prisma.SortOrder
  autoCalculate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TournamentResultCountOrderByAggregateInput
  _avg?: Prisma.TournamentResultAvgOrderByAggregateInput
  _max?: Prisma.TournamentResultMaxOrderByAggregateInput
  _min?: Prisma.TournamentResultMinOrderByAggregateInput
  _sum?: Prisma.TournamentResultSumOrderByAggregateInput
}

export type TournamentResultScalarWhereWithAggregatesInput = {
  AND?: Prisma.TournamentResultScalarWhereWithAggregatesInput | Prisma.TournamentResultScalarWhereWithAggregatesInput[]
  OR?: Prisma.TournamentResultScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TournamentResultScalarWhereWithAggregatesInput | Prisma.TournamentResultScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TournamentResult"> | string
  tournamentId?: Prisma.StringWithAggregatesFilter<"TournamentResult"> | string
  coachName?: Prisma.StringWithAggregatesFilter<"TournamentResult"> | string
  nafNumber?: Prisma.StringNullableWithAggregatesFilter<"TournamentResult"> | string | null
  userId?: Prisma.StringNullableWithAggregatesFilter<"TournamentResult"> | string | null
  roster?: Prisma.StringNullableWithAggregatesFilter<"TournamentResult"> | string | null
  wins?: Prisma.IntWithAggregatesFilter<"TournamentResult"> | number
  draws?: Prisma.IntWithAggregatesFilter<"TournamentResult"> | number
  losses?: Prisma.IntWithAggregatesFilter<"TournamentResult"> | number
  casualties?: Prisma.IntWithAggregatesFilter<"TournamentResult"> | number
  points?: Prisma.FloatWithAggregatesFilter<"TournamentResult"> | number
  rank?: Prisma.IntNullableWithAggregatesFilter<"TournamentResult"> | number | null
  autoCalculate?: Prisma.BoolWithAggregatesFilter<"TournamentResult"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TournamentResult"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TournamentResult"> | Date | string
}

export type TournamentResultCreateInput = {
  id?: string
  coachName: string
  nafNumber?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutTournamentResultsInput
  tournament: Prisma.TournamentCreateNestedOneWithoutResultsInput
}

export type TournamentResultUncheckedCreateInput = {
  id?: string
  tournamentId: string
  coachName: string
  nafNumber?: string | null
  userId?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentResultUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutTournamentResultsNestedInput
  tournament?: Prisma.TournamentUpdateOneRequiredWithoutResultsNestedInput
}

export type TournamentResultUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentResultCreateManyInput = {
  id?: string
  tournamentId: string
  coachName: string
  nafNumber?: string | null
  userId?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentResultUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentResultUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentResultListRelationFilter = {
  every?: Prisma.TournamentResultWhereInput
  some?: Prisma.TournamentResultWhereInput
  none?: Prisma.TournamentResultWhereInput
}

export type TournamentResultOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TournamentResultTournamentIdCoachNameCompoundUniqueInput = {
  tournamentId: string
  coachName: string
}

export type TournamentResultCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  coachName?: Prisma.SortOrder
  nafNumber?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roster?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  draws?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  casualties?: Prisma.SortOrder
  points?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  autoCalculate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentResultAvgOrderByAggregateInput = {
  wins?: Prisma.SortOrder
  draws?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  casualties?: Prisma.SortOrder
  points?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type TournamentResultMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  coachName?: Prisma.SortOrder
  nafNumber?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roster?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  draws?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  casualties?: Prisma.SortOrder
  points?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  autoCalculate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentResultMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  coachName?: Prisma.SortOrder
  nafNumber?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roster?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  draws?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  casualties?: Prisma.SortOrder
  points?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  autoCalculate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentResultSumOrderByAggregateInput = {
  wins?: Prisma.SortOrder
  draws?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  casualties?: Prisma.SortOrder
  points?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type TournamentResultCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TournamentResultCreateWithoutUserInput, Prisma.TournamentResultUncheckedCreateWithoutUserInput> | Prisma.TournamentResultCreateWithoutUserInput[] | Prisma.TournamentResultUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentResultCreateOrConnectWithoutUserInput | Prisma.TournamentResultCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TournamentResultCreateManyUserInputEnvelope
  connect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
}

export type TournamentResultUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TournamentResultCreateWithoutUserInput, Prisma.TournamentResultUncheckedCreateWithoutUserInput> | Prisma.TournamentResultCreateWithoutUserInput[] | Prisma.TournamentResultUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentResultCreateOrConnectWithoutUserInput | Prisma.TournamentResultCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TournamentResultCreateManyUserInputEnvelope
  connect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
}

export type TournamentResultUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentResultCreateWithoutUserInput, Prisma.TournamentResultUncheckedCreateWithoutUserInput> | Prisma.TournamentResultCreateWithoutUserInput[] | Prisma.TournamentResultUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentResultCreateOrConnectWithoutUserInput | Prisma.TournamentResultCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TournamentResultUpsertWithWhereUniqueWithoutUserInput | Prisma.TournamentResultUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TournamentResultCreateManyUserInputEnvelope
  set?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  disconnect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  delete?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  connect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  update?: Prisma.TournamentResultUpdateWithWhereUniqueWithoutUserInput | Prisma.TournamentResultUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TournamentResultUpdateManyWithWhereWithoutUserInput | Prisma.TournamentResultUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TournamentResultScalarWhereInput | Prisma.TournamentResultScalarWhereInput[]
}

export type TournamentResultUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentResultCreateWithoutUserInput, Prisma.TournamentResultUncheckedCreateWithoutUserInput> | Prisma.TournamentResultCreateWithoutUserInput[] | Prisma.TournamentResultUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentResultCreateOrConnectWithoutUserInput | Prisma.TournamentResultCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TournamentResultUpsertWithWhereUniqueWithoutUserInput | Prisma.TournamentResultUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TournamentResultCreateManyUserInputEnvelope
  set?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  disconnect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  delete?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  connect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  update?: Prisma.TournamentResultUpdateWithWhereUniqueWithoutUserInput | Prisma.TournamentResultUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TournamentResultUpdateManyWithWhereWithoutUserInput | Prisma.TournamentResultUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TournamentResultScalarWhereInput | Prisma.TournamentResultScalarWhereInput[]
}

export type TournamentResultCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TournamentResultCreateWithoutTournamentInput, Prisma.TournamentResultUncheckedCreateWithoutTournamentInput> | Prisma.TournamentResultCreateWithoutTournamentInput[] | Prisma.TournamentResultUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentResultCreateOrConnectWithoutTournamentInput | Prisma.TournamentResultCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TournamentResultCreateManyTournamentInputEnvelope
  connect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
}

export type TournamentResultUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TournamentResultCreateWithoutTournamentInput, Prisma.TournamentResultUncheckedCreateWithoutTournamentInput> | Prisma.TournamentResultCreateWithoutTournamentInput[] | Prisma.TournamentResultUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentResultCreateOrConnectWithoutTournamentInput | Prisma.TournamentResultCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TournamentResultCreateManyTournamentInputEnvelope
  connect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
}

export type TournamentResultUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentResultCreateWithoutTournamentInput, Prisma.TournamentResultUncheckedCreateWithoutTournamentInput> | Prisma.TournamentResultCreateWithoutTournamentInput[] | Prisma.TournamentResultUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentResultCreateOrConnectWithoutTournamentInput | Prisma.TournamentResultCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TournamentResultUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TournamentResultUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TournamentResultCreateManyTournamentInputEnvelope
  set?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  disconnect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  delete?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  connect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  update?: Prisma.TournamentResultUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TournamentResultUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TournamentResultUpdateManyWithWhereWithoutTournamentInput | Prisma.TournamentResultUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TournamentResultScalarWhereInput | Prisma.TournamentResultScalarWhereInput[]
}

export type TournamentResultUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentResultCreateWithoutTournamentInput, Prisma.TournamentResultUncheckedCreateWithoutTournamentInput> | Prisma.TournamentResultCreateWithoutTournamentInput[] | Prisma.TournamentResultUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentResultCreateOrConnectWithoutTournamentInput | Prisma.TournamentResultCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TournamentResultUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TournamentResultUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TournamentResultCreateManyTournamentInputEnvelope
  set?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  disconnect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  delete?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  connect?: Prisma.TournamentResultWhereUniqueInput | Prisma.TournamentResultWhereUniqueInput[]
  update?: Prisma.TournamentResultUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TournamentResultUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TournamentResultUpdateManyWithWhereWithoutTournamentInput | Prisma.TournamentResultUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TournamentResultScalarWhereInput | Prisma.TournamentResultScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TournamentResultCreateWithoutUserInput = {
  id?: string
  coachName: string
  nafNumber?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  tournament: Prisma.TournamentCreateNestedOneWithoutResultsInput
}

export type TournamentResultUncheckedCreateWithoutUserInput = {
  id?: string
  tournamentId: string
  coachName: string
  nafNumber?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentResultCreateOrConnectWithoutUserInput = {
  where: Prisma.TournamentResultWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentResultCreateWithoutUserInput, Prisma.TournamentResultUncheckedCreateWithoutUserInput>
}

export type TournamentResultCreateManyUserInputEnvelope = {
  data: Prisma.TournamentResultCreateManyUserInput | Prisma.TournamentResultCreateManyUserInput[]
}

export type TournamentResultUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TournamentResultWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentResultUpdateWithoutUserInput, Prisma.TournamentResultUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TournamentResultCreateWithoutUserInput, Prisma.TournamentResultUncheckedCreateWithoutUserInput>
}

export type TournamentResultUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TournamentResultWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentResultUpdateWithoutUserInput, Prisma.TournamentResultUncheckedUpdateWithoutUserInput>
}

export type TournamentResultUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TournamentResultScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentResultUpdateManyMutationInput, Prisma.TournamentResultUncheckedUpdateManyWithoutUserInput>
}

export type TournamentResultScalarWhereInput = {
  AND?: Prisma.TournamentResultScalarWhereInput | Prisma.TournamentResultScalarWhereInput[]
  OR?: Prisma.TournamentResultScalarWhereInput[]
  NOT?: Prisma.TournamentResultScalarWhereInput | Prisma.TournamentResultScalarWhereInput[]
  id?: Prisma.StringFilter<"TournamentResult"> | string
  tournamentId?: Prisma.StringFilter<"TournamentResult"> | string
  coachName?: Prisma.StringFilter<"TournamentResult"> | string
  nafNumber?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  userId?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  roster?: Prisma.StringNullableFilter<"TournamentResult"> | string | null
  wins?: Prisma.IntFilter<"TournamentResult"> | number
  draws?: Prisma.IntFilter<"TournamentResult"> | number
  losses?: Prisma.IntFilter<"TournamentResult"> | number
  casualties?: Prisma.IntFilter<"TournamentResult"> | number
  points?: Prisma.FloatFilter<"TournamentResult"> | number
  rank?: Prisma.IntNullableFilter<"TournamentResult"> | number | null
  autoCalculate?: Prisma.BoolFilter<"TournamentResult"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TournamentResult"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentResult"> | Date | string
}

export type TournamentResultCreateWithoutTournamentInput = {
  id?: string
  coachName: string
  nafNumber?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutTournamentResultsInput
}

export type TournamentResultUncheckedCreateWithoutTournamentInput = {
  id?: string
  coachName: string
  nafNumber?: string | null
  userId?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentResultCreateOrConnectWithoutTournamentInput = {
  where: Prisma.TournamentResultWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentResultCreateWithoutTournamentInput, Prisma.TournamentResultUncheckedCreateWithoutTournamentInput>
}

export type TournamentResultCreateManyTournamentInputEnvelope = {
  data: Prisma.TournamentResultCreateManyTournamentInput | Prisma.TournamentResultCreateManyTournamentInput[]
}

export type TournamentResultUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TournamentResultWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentResultUpdateWithoutTournamentInput, Prisma.TournamentResultUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.TournamentResultCreateWithoutTournamentInput, Prisma.TournamentResultUncheckedCreateWithoutTournamentInput>
}

export type TournamentResultUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TournamentResultWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentResultUpdateWithoutTournamentInput, Prisma.TournamentResultUncheckedUpdateWithoutTournamentInput>
}

export type TournamentResultUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.TournamentResultScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentResultUpdateManyMutationInput, Prisma.TournamentResultUncheckedUpdateManyWithoutTournamentInput>
}

export type TournamentResultCreateManyUserInput = {
  id?: string
  tournamentId: string
  coachName: string
  nafNumber?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentResultUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournament?: Prisma.TournamentUpdateOneRequiredWithoutResultsNestedInput
}

export type TournamentResultUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentResultUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentResultCreateManyTournamentInput = {
  id?: string
  coachName: string
  nafNumber?: string | null
  userId?: string | null
  roster?: string | null
  wins?: number
  draws?: number
  losses?: number
  casualties?: number
  points?: number
  rank?: number | null
  autoCalculate?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentResultUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutTournamentResultsNestedInput
}

export type TournamentResultUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentResultUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coachName?: Prisma.StringFieldUpdateOperationsInput | string
  nafNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roster?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  draws?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  casualties?: Prisma.IntFieldUpdateOperationsInput | number
  points?: Prisma.FloatFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  autoCalculate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TournamentResultSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  coachName?: boolean
  nafNumber?: boolean
  userId?: boolean
  roster?: boolean
  wins?: boolean
  draws?: boolean
  losses?: boolean
  casualties?: boolean
  points?: boolean
  rank?: boolean
  autoCalculate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.TournamentResult$userArgs<ExtArgs>
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentResult"]>

export type TournamentResultSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  coachName?: boolean
  nafNumber?: boolean
  userId?: boolean
  roster?: boolean
  wins?: boolean
  draws?: boolean
  losses?: boolean
  casualties?: boolean
  points?: boolean
  rank?: boolean
  autoCalculate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.TournamentResult$userArgs<ExtArgs>
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentResult"]>

export type TournamentResultSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  coachName?: boolean
  nafNumber?: boolean
  userId?: boolean
  roster?: boolean
  wins?: boolean
  draws?: boolean
  losses?: boolean
  casualties?: boolean
  points?: boolean
  rank?: boolean
  autoCalculate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.TournamentResult$userArgs<ExtArgs>
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentResult"]>

export type TournamentResultSelectScalar = {
  id?: boolean
  tournamentId?: boolean
  coachName?: boolean
  nafNumber?: boolean
  userId?: boolean
  roster?: boolean
  wins?: boolean
  draws?: boolean
  losses?: boolean
  casualties?: boolean
  points?: boolean
  rank?: boolean
  autoCalculate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TournamentResultOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "coachName" | "nafNumber" | "userId" | "roster" | "wins" | "draws" | "losses" | "casualties" | "points" | "rank" | "autoCalculate" | "createdAt" | "updatedAt", ExtArgs["result"]["tournamentResult"]>
export type TournamentResultInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.TournamentResult$userArgs<ExtArgs>
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}
export type TournamentResultIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.TournamentResult$userArgs<ExtArgs>
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}
export type TournamentResultIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.TournamentResult$userArgs<ExtArgs>
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}

export type $TournamentResultPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TournamentResult"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
    tournament: Prisma.$TournamentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tournamentId: string
    coachName: string
    nafNumber: string | null
    userId: string | null
    roster: string | null
    wins: number
    draws: number
    losses: number
    casualties: number
    points: number
    rank: number | null
    autoCalculate: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tournamentResult"]>
  composites: {}
}

export type TournamentResultGetPayload<S extends boolean | null | undefined | TournamentResultDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload, S>

export type TournamentResultCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TournamentResultFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TournamentResultCountAggregateInputType | true
  }

export interface TournamentResultDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TournamentResult'], meta: { name: 'TournamentResult' } }
  /**
   * Find zero or one TournamentResult that matches the filter.
   * @param {TournamentResultFindUniqueArgs} args - Arguments to find a TournamentResult
   * @example
   * // Get one TournamentResult
   * const tournamentResult = await prisma.tournamentResult.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TournamentResultFindUniqueArgs>(args: Prisma.SelectSubset<T, TournamentResultFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TournamentResultClient<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TournamentResult that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TournamentResultFindUniqueOrThrowArgs} args - Arguments to find a TournamentResult
   * @example
   * // Get one TournamentResult
   * const tournamentResult = await prisma.tournamentResult.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TournamentResultFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TournamentResultFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentResultClient<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentResult that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentResultFindFirstArgs} args - Arguments to find a TournamentResult
   * @example
   * // Get one TournamentResult
   * const tournamentResult = await prisma.tournamentResult.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TournamentResultFindFirstArgs>(args?: Prisma.SelectSubset<T, TournamentResultFindFirstArgs<ExtArgs>>): Prisma.Prisma__TournamentResultClient<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentResult that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentResultFindFirstOrThrowArgs} args - Arguments to find a TournamentResult
   * @example
   * // Get one TournamentResult
   * const tournamentResult = await prisma.tournamentResult.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TournamentResultFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TournamentResultFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentResultClient<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TournamentResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentResultFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TournamentResults
   * const tournamentResults = await prisma.tournamentResult.findMany()
   * 
   * // Get first 10 TournamentResults
   * const tournamentResults = await prisma.tournamentResult.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tournamentResultWithIdOnly = await prisma.tournamentResult.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TournamentResultFindManyArgs>(args?: Prisma.SelectSubset<T, TournamentResultFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TournamentResult.
   * @param {TournamentResultCreateArgs} args - Arguments to create a TournamentResult.
   * @example
   * // Create one TournamentResult
   * const TournamentResult = await prisma.tournamentResult.create({
   *   data: {
   *     // ... data to create a TournamentResult
   *   }
   * })
   * 
   */
  create<T extends TournamentResultCreateArgs>(args: Prisma.SelectSubset<T, TournamentResultCreateArgs<ExtArgs>>): Prisma.Prisma__TournamentResultClient<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TournamentResults.
   * @param {TournamentResultCreateManyArgs} args - Arguments to create many TournamentResults.
   * @example
   * // Create many TournamentResults
   * const tournamentResult = await prisma.tournamentResult.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TournamentResultCreateManyArgs>(args?: Prisma.SelectSubset<T, TournamentResultCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TournamentResults and returns the data saved in the database.
   * @param {TournamentResultCreateManyAndReturnArgs} args - Arguments to create many TournamentResults.
   * @example
   * // Create many TournamentResults
   * const tournamentResult = await prisma.tournamentResult.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TournamentResults and only return the `id`
   * const tournamentResultWithIdOnly = await prisma.tournamentResult.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TournamentResultCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TournamentResultCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TournamentResult.
   * @param {TournamentResultDeleteArgs} args - Arguments to delete one TournamentResult.
   * @example
   * // Delete one TournamentResult
   * const TournamentResult = await prisma.tournamentResult.delete({
   *   where: {
   *     // ... filter to delete one TournamentResult
   *   }
   * })
   * 
   */
  delete<T extends TournamentResultDeleteArgs>(args: Prisma.SelectSubset<T, TournamentResultDeleteArgs<ExtArgs>>): Prisma.Prisma__TournamentResultClient<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TournamentResult.
   * @param {TournamentResultUpdateArgs} args - Arguments to update one TournamentResult.
   * @example
   * // Update one TournamentResult
   * const tournamentResult = await prisma.tournamentResult.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TournamentResultUpdateArgs>(args: Prisma.SelectSubset<T, TournamentResultUpdateArgs<ExtArgs>>): Prisma.Prisma__TournamentResultClient<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TournamentResults.
   * @param {TournamentResultDeleteManyArgs} args - Arguments to filter TournamentResults to delete.
   * @example
   * // Delete a few TournamentResults
   * const { count } = await prisma.tournamentResult.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TournamentResultDeleteManyArgs>(args?: Prisma.SelectSubset<T, TournamentResultDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentResultUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TournamentResults
   * const tournamentResult = await prisma.tournamentResult.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TournamentResultUpdateManyArgs>(args: Prisma.SelectSubset<T, TournamentResultUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentResults and returns the data updated in the database.
   * @param {TournamentResultUpdateManyAndReturnArgs} args - Arguments to update many TournamentResults.
   * @example
   * // Update many TournamentResults
   * const tournamentResult = await prisma.tournamentResult.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TournamentResults and only return the `id`
   * const tournamentResultWithIdOnly = await prisma.tournamentResult.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TournamentResultUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TournamentResultUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TournamentResult.
   * @param {TournamentResultUpsertArgs} args - Arguments to update or create a TournamentResult.
   * @example
   * // Update or create a TournamentResult
   * const tournamentResult = await prisma.tournamentResult.upsert({
   *   create: {
   *     // ... data to create a TournamentResult
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TournamentResult we want to update
   *   }
   * })
   */
  upsert<T extends TournamentResultUpsertArgs>(args: Prisma.SelectSubset<T, TournamentResultUpsertArgs<ExtArgs>>): Prisma.Prisma__TournamentResultClient<runtime.Types.Result.GetResult<Prisma.$TournamentResultPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TournamentResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentResultCountArgs} args - Arguments to filter TournamentResults to count.
   * @example
   * // Count the number of TournamentResults
   * const count = await prisma.tournamentResult.count({
   *   where: {
   *     // ... the filter for the TournamentResults we want to count
   *   }
   * })
  **/
  count<T extends TournamentResultCountArgs>(
    args?: Prisma.Subset<T, TournamentResultCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TournamentResultCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TournamentResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentResultAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TournamentResultAggregateArgs>(args: Prisma.Subset<T, TournamentResultAggregateArgs>): Prisma.PrismaPromise<GetTournamentResultAggregateType<T>>

  /**
   * Group by TournamentResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentResultGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TournamentResultGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TournamentResultGroupByArgs['orderBy'] }
      : { orderBy?: TournamentResultGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TournamentResultGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTournamentResultGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TournamentResult model
 */
readonly fields: TournamentResultFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TournamentResult.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TournamentResultClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.TournamentResult$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentResult$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  tournament<T extends Prisma.TournamentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TournamentResult model
 */
export interface TournamentResultFieldRefs {
  readonly id: Prisma.FieldRef<"TournamentResult", 'String'>
  readonly tournamentId: Prisma.FieldRef<"TournamentResult", 'String'>
  readonly coachName: Prisma.FieldRef<"TournamentResult", 'String'>
  readonly nafNumber: Prisma.FieldRef<"TournamentResult", 'String'>
  readonly userId: Prisma.FieldRef<"TournamentResult", 'String'>
  readonly roster: Prisma.FieldRef<"TournamentResult", 'String'>
  readonly wins: Prisma.FieldRef<"TournamentResult", 'Int'>
  readonly draws: Prisma.FieldRef<"TournamentResult", 'Int'>
  readonly losses: Prisma.FieldRef<"TournamentResult", 'Int'>
  readonly casualties: Prisma.FieldRef<"TournamentResult", 'Int'>
  readonly points: Prisma.FieldRef<"TournamentResult", 'Float'>
  readonly rank: Prisma.FieldRef<"TournamentResult", 'Int'>
  readonly autoCalculate: Prisma.FieldRef<"TournamentResult", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"TournamentResult", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TournamentResult", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TournamentResult findUnique
 */
export type TournamentResultFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * Filter, which TournamentResult to fetch.
   */
  where: Prisma.TournamentResultWhereUniqueInput
}

/**
 * TournamentResult findUniqueOrThrow
 */
export type TournamentResultFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * Filter, which TournamentResult to fetch.
   */
  where: Prisma.TournamentResultWhereUniqueInput
}

/**
 * TournamentResult findFirst
 */
export type TournamentResultFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * Filter, which TournamentResult to fetch.
   */
  where?: Prisma.TournamentResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentResults to fetch.
   */
  orderBy?: Prisma.TournamentResultOrderByWithRelationInput | Prisma.TournamentResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentResults.
   */
  cursor?: Prisma.TournamentResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentResults.
   */
  distinct?: Prisma.TournamentResultScalarFieldEnum | Prisma.TournamentResultScalarFieldEnum[]
}

/**
 * TournamentResult findFirstOrThrow
 */
export type TournamentResultFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * Filter, which TournamentResult to fetch.
   */
  where?: Prisma.TournamentResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentResults to fetch.
   */
  orderBy?: Prisma.TournamentResultOrderByWithRelationInput | Prisma.TournamentResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentResults.
   */
  cursor?: Prisma.TournamentResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentResults.
   */
  distinct?: Prisma.TournamentResultScalarFieldEnum | Prisma.TournamentResultScalarFieldEnum[]
}

/**
 * TournamentResult findMany
 */
export type TournamentResultFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * Filter, which TournamentResults to fetch.
   */
  where?: Prisma.TournamentResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentResults to fetch.
   */
  orderBy?: Prisma.TournamentResultOrderByWithRelationInput | Prisma.TournamentResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TournamentResults.
   */
  cursor?: Prisma.TournamentResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentResults.
   */
  distinct?: Prisma.TournamentResultScalarFieldEnum | Prisma.TournamentResultScalarFieldEnum[]
}

/**
 * TournamentResult create
 */
export type TournamentResultCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * The data needed to create a TournamentResult.
   */
  data: Prisma.XOR<Prisma.TournamentResultCreateInput, Prisma.TournamentResultUncheckedCreateInput>
}

/**
 * TournamentResult createMany
 */
export type TournamentResultCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TournamentResults.
   */
  data: Prisma.TournamentResultCreateManyInput | Prisma.TournamentResultCreateManyInput[]
}

/**
 * TournamentResult createManyAndReturn
 */
export type TournamentResultCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * The data used to create many TournamentResults.
   */
  data: Prisma.TournamentResultCreateManyInput | Prisma.TournamentResultCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentResult update
 */
export type TournamentResultUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * The data needed to update a TournamentResult.
   */
  data: Prisma.XOR<Prisma.TournamentResultUpdateInput, Prisma.TournamentResultUncheckedUpdateInput>
  /**
   * Choose, which TournamentResult to update.
   */
  where: Prisma.TournamentResultWhereUniqueInput
}

/**
 * TournamentResult updateMany
 */
export type TournamentResultUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TournamentResults.
   */
  data: Prisma.XOR<Prisma.TournamentResultUpdateManyMutationInput, Prisma.TournamentResultUncheckedUpdateManyInput>
  /**
   * Filter which TournamentResults to update
   */
  where?: Prisma.TournamentResultWhereInput
  /**
   * Limit how many TournamentResults to update.
   */
  limit?: number
}

/**
 * TournamentResult updateManyAndReturn
 */
export type TournamentResultUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * The data used to update TournamentResults.
   */
  data: Prisma.XOR<Prisma.TournamentResultUpdateManyMutationInput, Prisma.TournamentResultUncheckedUpdateManyInput>
  /**
   * Filter which TournamentResults to update
   */
  where?: Prisma.TournamentResultWhereInput
  /**
   * Limit how many TournamentResults to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentResult upsert
 */
export type TournamentResultUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * The filter to search for the TournamentResult to update in case it exists.
   */
  where: Prisma.TournamentResultWhereUniqueInput
  /**
   * In case the TournamentResult found by the `where` argument doesn't exist, create a new TournamentResult with this data.
   */
  create: Prisma.XOR<Prisma.TournamentResultCreateInput, Prisma.TournamentResultUncheckedCreateInput>
  /**
   * In case the TournamentResult was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TournamentResultUpdateInput, Prisma.TournamentResultUncheckedUpdateInput>
}

/**
 * TournamentResult delete
 */
export type TournamentResultDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
  /**
   * Filter which TournamentResult to delete.
   */
  where: Prisma.TournamentResultWhereUniqueInput
}

/**
 * TournamentResult deleteMany
 */
export type TournamentResultDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentResults to delete
   */
  where?: Prisma.TournamentResultWhereInput
  /**
   * Limit how many TournamentResults to delete.
   */
  limit?: number
}

/**
 * TournamentResult.user
 */
export type TournamentResult$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * TournamentResult without action
 */
export type TournamentResultDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentResult
   */
  select?: Prisma.TournamentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentResult
   */
  omit?: Prisma.TournamentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentResultInclude<ExtArgs> | null
}
