
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TournamentMatch` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TournamentMatch
 * 
 */
export type TournamentMatchModel = runtime.Types.Result.DefaultSelection<Prisma.$TournamentMatchPayload>

export type AggregateTournamentMatch = {
  _count: TournamentMatchCountAggregateOutputType | null
  _avg: TournamentMatchAvgAggregateOutputType | null
  _sum: TournamentMatchSumAggregateOutputType | null
  _min: TournamentMatchMinAggregateOutputType | null
  _max: TournamentMatchMaxAggregateOutputType | null
}

export type TournamentMatchAvgAggregateOutputType = {
  tableNumber: number | null
  coach1TD: number | null
  coach1Casualties: number | null
  coach2TD: number | null
  coach2Casualties: number | null
}

export type TournamentMatchSumAggregateOutputType = {
  tableNumber: number | null
  coach1TD: number | null
  coach1Casualties: number | null
  coach2TD: number | null
  coach2Casualties: number | null
}

export type TournamentMatchMinAggregateOutputType = {
  id: string | null
  roundId: string | null
  tableNumber: number | null
  coach1Name: string | null
  coach1UserId: string | null
  coach2Name: string | null
  coach2UserId: string | null
  coach1TD: number | null
  coach1Casualties: number | null
  coach2TD: number | null
  coach2Casualties: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TournamentMatchMaxAggregateOutputType = {
  id: string | null
  roundId: string | null
  tableNumber: number | null
  coach1Name: string | null
  coach1UserId: string | null
  coach2Name: string | null
  coach2UserId: string | null
  coach1TD: number | null
  coach1Casualties: number | null
  coach2TD: number | null
  coach2Casualties: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TournamentMatchCountAggregateOutputType = {
  id: number
  roundId: number
  tableNumber: number
  coach1Name: number
  coach1UserId: number
  coach2Name: number
  coach2UserId: number
  coach1TD: number
  coach1Casualties: number
  coach2TD: number
  coach2Casualties: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TournamentMatchAvgAggregateInputType = {
  tableNumber?: true
  coach1TD?: true
  coach1Casualties?: true
  coach2TD?: true
  coach2Casualties?: true
}

export type TournamentMatchSumAggregateInputType = {
  tableNumber?: true
  coach1TD?: true
  coach1Casualties?: true
  coach2TD?: true
  coach2Casualties?: true
}

export type TournamentMatchMinAggregateInputType = {
  id?: true
  roundId?: true
  tableNumber?: true
  coach1Name?: true
  coach1UserId?: true
  coach2Name?: true
  coach2UserId?: true
  coach1TD?: true
  coach1Casualties?: true
  coach2TD?: true
  coach2Casualties?: true
  createdAt?: true
  updatedAt?: true
}

export type TournamentMatchMaxAggregateInputType = {
  id?: true
  roundId?: true
  tableNumber?: true
  coach1Name?: true
  coach1UserId?: true
  coach2Name?: true
  coach2UserId?: true
  coach1TD?: true
  coach1Casualties?: true
  coach2TD?: true
  coach2Casualties?: true
  createdAt?: true
  updatedAt?: true
}

export type TournamentMatchCountAggregateInputType = {
  id?: true
  roundId?: true
  tableNumber?: true
  coach1Name?: true
  coach1UserId?: true
  coach2Name?: true
  coach2UserId?: true
  coach1TD?: true
  coach1Casualties?: true
  coach2TD?: true
  coach2Casualties?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TournamentMatchAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentMatch to aggregate.
   */
  where?: Prisma.TournamentMatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentMatches to fetch.
   */
  orderBy?: Prisma.TournamentMatchOrderByWithRelationInput | Prisma.TournamentMatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TournamentMatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentMatches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentMatches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TournamentMatches
  **/
  _count?: true | TournamentMatchCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TournamentMatchAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TournamentMatchSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TournamentMatchMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TournamentMatchMaxAggregateInputType
}

export type GetTournamentMatchAggregateType<T extends TournamentMatchAggregateArgs> = {
      [P in keyof T & keyof AggregateTournamentMatch]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTournamentMatch[P]>
    : Prisma.GetScalarType<T[P], AggregateTournamentMatch[P]>
}




export type TournamentMatchGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TournamentMatchWhereInput
  orderBy?: Prisma.TournamentMatchOrderByWithAggregationInput | Prisma.TournamentMatchOrderByWithAggregationInput[]
  by: Prisma.TournamentMatchScalarFieldEnum[] | Prisma.TournamentMatchScalarFieldEnum
  having?: Prisma.TournamentMatchScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TournamentMatchCountAggregateInputType | true
  _avg?: TournamentMatchAvgAggregateInputType
  _sum?: TournamentMatchSumAggregateInputType
  _min?: TournamentMatchMinAggregateInputType
  _max?: TournamentMatchMaxAggregateInputType
}

export type TournamentMatchGroupByOutputType = {
  id: string
  roundId: string
  tableNumber: number | null
  coach1Name: string
  coach1UserId: string | null
  coach2Name: string
  coach2UserId: string | null
  coach1TD: number
  coach1Casualties: number
  coach2TD: number
  coach2Casualties: number
  createdAt: Date
  updatedAt: Date
  _count: TournamentMatchCountAggregateOutputType | null
  _avg: TournamentMatchAvgAggregateOutputType | null
  _sum: TournamentMatchSumAggregateOutputType | null
  _min: TournamentMatchMinAggregateOutputType | null
  _max: TournamentMatchMaxAggregateOutputType | null
}

type GetTournamentMatchGroupByPayload<T extends TournamentMatchGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TournamentMatchGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TournamentMatchGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TournamentMatchGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TournamentMatchGroupByOutputType[P]>
      }
    >
  >



export type TournamentMatchWhereInput = {
  AND?: Prisma.TournamentMatchWhereInput | Prisma.TournamentMatchWhereInput[]
  OR?: Prisma.TournamentMatchWhereInput[]
  NOT?: Prisma.TournamentMatchWhereInput | Prisma.TournamentMatchWhereInput[]
  id?: Prisma.StringFilter<"TournamentMatch"> | string
  roundId?: Prisma.StringFilter<"TournamentMatch"> | string
  tableNumber?: Prisma.IntNullableFilter<"TournamentMatch"> | number | null
  coach1Name?: Prisma.StringFilter<"TournamentMatch"> | string
  coach1UserId?: Prisma.StringNullableFilter<"TournamentMatch"> | string | null
  coach2Name?: Prisma.StringFilter<"TournamentMatch"> | string
  coach2UserId?: Prisma.StringNullableFilter<"TournamentMatch"> | string | null
  coach1TD?: Prisma.IntFilter<"TournamentMatch"> | number
  coach1Casualties?: Prisma.IntFilter<"TournamentMatch"> | number
  coach2TD?: Prisma.IntFilter<"TournamentMatch"> | number
  coach2Casualties?: Prisma.IntFilter<"TournamentMatch"> | number
  createdAt?: Prisma.DateTimeFilter<"TournamentMatch"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentMatch"> | Date | string
  coach2User?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  coach1User?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  round?: Prisma.XOR<Prisma.TournamentRoundScalarRelationFilter, Prisma.TournamentRoundWhereInput>
}

export type TournamentMatchOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  tableNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  coach1Name?: Prisma.SortOrder
  coach1UserId?: Prisma.SortOrderInput | Prisma.SortOrder
  coach2Name?: Prisma.SortOrder
  coach2UserId?: Prisma.SortOrderInput | Prisma.SortOrder
  coach1TD?: Prisma.SortOrder
  coach1Casualties?: Prisma.SortOrder
  coach2TD?: Prisma.SortOrder
  coach2Casualties?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  coach2User?: Prisma.UserOrderByWithRelationInput
  coach1User?: Prisma.UserOrderByWithRelationInput
  round?: Prisma.TournamentRoundOrderByWithRelationInput
}

export type TournamentMatchWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TournamentMatchWhereInput | Prisma.TournamentMatchWhereInput[]
  OR?: Prisma.TournamentMatchWhereInput[]
  NOT?: Prisma.TournamentMatchWhereInput | Prisma.TournamentMatchWhereInput[]
  roundId?: Prisma.StringFilter<"TournamentMatch"> | string
  tableNumber?: Prisma.IntNullableFilter<"TournamentMatch"> | number | null
  coach1Name?: Prisma.StringFilter<"TournamentMatch"> | string
  coach1UserId?: Prisma.StringNullableFilter<"TournamentMatch"> | string | null
  coach2Name?: Prisma.StringFilter<"TournamentMatch"> | string
  coach2UserId?: Prisma.StringNullableFilter<"TournamentMatch"> | string | null
  coach1TD?: Prisma.IntFilter<"TournamentMatch"> | number
  coach1Casualties?: Prisma.IntFilter<"TournamentMatch"> | number
  coach2TD?: Prisma.IntFilter<"TournamentMatch"> | number
  coach2Casualties?: Prisma.IntFilter<"TournamentMatch"> | number
  createdAt?: Prisma.DateTimeFilter<"TournamentMatch"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentMatch"> | Date | string
  coach2User?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  coach1User?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  round?: Prisma.XOR<Prisma.TournamentRoundScalarRelationFilter, Prisma.TournamentRoundWhereInput>
}, "id">

export type TournamentMatchOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  tableNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  coach1Name?: Prisma.SortOrder
  coach1UserId?: Prisma.SortOrderInput | Prisma.SortOrder
  coach2Name?: Prisma.SortOrder
  coach2UserId?: Prisma.SortOrderInput | Prisma.SortOrder
  coach1TD?: Prisma.SortOrder
  coach1Casualties?: Prisma.SortOrder
  coach2TD?: Prisma.SortOrder
  coach2Casualties?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TournamentMatchCountOrderByAggregateInput
  _avg?: Prisma.TournamentMatchAvgOrderByAggregateInput
  _max?: Prisma.TournamentMatchMaxOrderByAggregateInput
  _min?: Prisma.TournamentMatchMinOrderByAggregateInput
  _sum?: Prisma.TournamentMatchSumOrderByAggregateInput
}

export type TournamentMatchScalarWhereWithAggregatesInput = {
  AND?: Prisma.TournamentMatchScalarWhereWithAggregatesInput | Prisma.TournamentMatchScalarWhereWithAggregatesInput[]
  OR?: Prisma.TournamentMatchScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TournamentMatchScalarWhereWithAggregatesInput | Prisma.TournamentMatchScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TournamentMatch"> | string
  roundId?: Prisma.StringWithAggregatesFilter<"TournamentMatch"> | string
  tableNumber?: Prisma.IntNullableWithAggregatesFilter<"TournamentMatch"> | number | null
  coach1Name?: Prisma.StringWithAggregatesFilter<"TournamentMatch"> | string
  coach1UserId?: Prisma.StringNullableWithAggregatesFilter<"TournamentMatch"> | string | null
  coach2Name?: Prisma.StringWithAggregatesFilter<"TournamentMatch"> | string
  coach2UserId?: Prisma.StringNullableWithAggregatesFilter<"TournamentMatch"> | string | null
  coach1TD?: Prisma.IntWithAggregatesFilter<"TournamentMatch"> | number
  coach1Casualties?: Prisma.IntWithAggregatesFilter<"TournamentMatch"> | number
  coach2TD?: Prisma.IntWithAggregatesFilter<"TournamentMatch"> | number
  coach2Casualties?: Prisma.IntWithAggregatesFilter<"TournamentMatch"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TournamentMatch"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TournamentMatch"> | Date | string
}

export type TournamentMatchCreateInput = {
  id?: string
  tableNumber?: number | null
  coach1Name: string
  coach2Name: string
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  coach2User?: Prisma.UserCreateNestedOneWithoutMatchesAsCoach2Input
  coach1User?: Prisma.UserCreateNestedOneWithoutMatchesAsCoach1Input
  round: Prisma.TournamentRoundCreateNestedOneWithoutMatchesInput
}

export type TournamentMatchUncheckedCreateInput = {
  id?: string
  roundId: string
  tableNumber?: number | null
  coach1Name: string
  coach1UserId?: string | null
  coach2Name: string
  coach2UserId?: string | null
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentMatchUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coach2User?: Prisma.UserUpdateOneWithoutMatchesAsCoach2NestedInput
  coach1User?: Prisma.UserUpdateOneWithoutMatchesAsCoach1NestedInput
  round?: Prisma.TournamentRoundUpdateOneRequiredWithoutMatchesNestedInput
}

export type TournamentMatchUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentMatchCreateManyInput = {
  id?: string
  roundId: string
  tableNumber?: number | null
  coach1Name: string
  coach1UserId?: string | null
  coach2Name: string
  coach2UserId?: string | null
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentMatchUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentMatchUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentMatchListRelationFilter = {
  every?: Prisma.TournamentMatchWhereInput
  some?: Prisma.TournamentMatchWhereInput
  none?: Prisma.TournamentMatchWhereInput
}

export type TournamentMatchOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TournamentMatchCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  tableNumber?: Prisma.SortOrder
  coach1Name?: Prisma.SortOrder
  coach1UserId?: Prisma.SortOrder
  coach2Name?: Prisma.SortOrder
  coach2UserId?: Prisma.SortOrder
  coach1TD?: Prisma.SortOrder
  coach1Casualties?: Prisma.SortOrder
  coach2TD?: Prisma.SortOrder
  coach2Casualties?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentMatchAvgOrderByAggregateInput = {
  tableNumber?: Prisma.SortOrder
  coach1TD?: Prisma.SortOrder
  coach1Casualties?: Prisma.SortOrder
  coach2TD?: Prisma.SortOrder
  coach2Casualties?: Prisma.SortOrder
}

export type TournamentMatchMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  tableNumber?: Prisma.SortOrder
  coach1Name?: Prisma.SortOrder
  coach1UserId?: Prisma.SortOrder
  coach2Name?: Prisma.SortOrder
  coach2UserId?: Prisma.SortOrder
  coach1TD?: Prisma.SortOrder
  coach1Casualties?: Prisma.SortOrder
  coach2TD?: Prisma.SortOrder
  coach2Casualties?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentMatchMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  tableNumber?: Prisma.SortOrder
  coach1Name?: Prisma.SortOrder
  coach1UserId?: Prisma.SortOrder
  coach2Name?: Prisma.SortOrder
  coach2UserId?: Prisma.SortOrder
  coach1TD?: Prisma.SortOrder
  coach1Casualties?: Prisma.SortOrder
  coach2TD?: Prisma.SortOrder
  coach2Casualties?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentMatchSumOrderByAggregateInput = {
  tableNumber?: Prisma.SortOrder
  coach1TD?: Prisma.SortOrder
  coach1Casualties?: Prisma.SortOrder
  coach2TD?: Prisma.SortOrder
  coach2Casualties?: Prisma.SortOrder
}

export type TournamentMatchCreateNestedManyWithoutCoach2UserInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach2UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput> | Prisma.TournamentMatchCreateWithoutCoach2UserInput[] | Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutCoach2UserInput | Prisma.TournamentMatchCreateOrConnectWithoutCoach2UserInput[]
  createMany?: Prisma.TournamentMatchCreateManyCoach2UserInputEnvelope
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
}

export type TournamentMatchCreateNestedManyWithoutCoach1UserInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach1UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput> | Prisma.TournamentMatchCreateWithoutCoach1UserInput[] | Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutCoach1UserInput | Prisma.TournamentMatchCreateOrConnectWithoutCoach1UserInput[]
  createMany?: Prisma.TournamentMatchCreateManyCoach1UserInputEnvelope
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
}

export type TournamentMatchUncheckedCreateNestedManyWithoutCoach2UserInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach2UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput> | Prisma.TournamentMatchCreateWithoutCoach2UserInput[] | Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutCoach2UserInput | Prisma.TournamentMatchCreateOrConnectWithoutCoach2UserInput[]
  createMany?: Prisma.TournamentMatchCreateManyCoach2UserInputEnvelope
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
}

export type TournamentMatchUncheckedCreateNestedManyWithoutCoach1UserInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach1UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput> | Prisma.TournamentMatchCreateWithoutCoach1UserInput[] | Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutCoach1UserInput | Prisma.TournamentMatchCreateOrConnectWithoutCoach1UserInput[]
  createMany?: Prisma.TournamentMatchCreateManyCoach1UserInputEnvelope
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
}

export type TournamentMatchUpdateManyWithoutCoach2UserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach2UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput> | Prisma.TournamentMatchCreateWithoutCoach2UserInput[] | Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutCoach2UserInput | Prisma.TournamentMatchCreateOrConnectWithoutCoach2UserInput[]
  upsert?: Prisma.TournamentMatchUpsertWithWhereUniqueWithoutCoach2UserInput | Prisma.TournamentMatchUpsertWithWhereUniqueWithoutCoach2UserInput[]
  createMany?: Prisma.TournamentMatchCreateManyCoach2UserInputEnvelope
  set?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  disconnect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  delete?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  update?: Prisma.TournamentMatchUpdateWithWhereUniqueWithoutCoach2UserInput | Prisma.TournamentMatchUpdateWithWhereUniqueWithoutCoach2UserInput[]
  updateMany?: Prisma.TournamentMatchUpdateManyWithWhereWithoutCoach2UserInput | Prisma.TournamentMatchUpdateManyWithWhereWithoutCoach2UserInput[]
  deleteMany?: Prisma.TournamentMatchScalarWhereInput | Prisma.TournamentMatchScalarWhereInput[]
}

export type TournamentMatchUpdateManyWithoutCoach1UserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach1UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput> | Prisma.TournamentMatchCreateWithoutCoach1UserInput[] | Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutCoach1UserInput | Prisma.TournamentMatchCreateOrConnectWithoutCoach1UserInput[]
  upsert?: Prisma.TournamentMatchUpsertWithWhereUniqueWithoutCoach1UserInput | Prisma.TournamentMatchUpsertWithWhereUniqueWithoutCoach1UserInput[]
  createMany?: Prisma.TournamentMatchCreateManyCoach1UserInputEnvelope
  set?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  disconnect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  delete?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  update?: Prisma.TournamentMatchUpdateWithWhereUniqueWithoutCoach1UserInput | Prisma.TournamentMatchUpdateWithWhereUniqueWithoutCoach1UserInput[]
  updateMany?: Prisma.TournamentMatchUpdateManyWithWhereWithoutCoach1UserInput | Prisma.TournamentMatchUpdateManyWithWhereWithoutCoach1UserInput[]
  deleteMany?: Prisma.TournamentMatchScalarWhereInput | Prisma.TournamentMatchScalarWhereInput[]
}

export type TournamentMatchUncheckedUpdateManyWithoutCoach2UserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach2UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput> | Prisma.TournamentMatchCreateWithoutCoach2UserInput[] | Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutCoach2UserInput | Prisma.TournamentMatchCreateOrConnectWithoutCoach2UserInput[]
  upsert?: Prisma.TournamentMatchUpsertWithWhereUniqueWithoutCoach2UserInput | Prisma.TournamentMatchUpsertWithWhereUniqueWithoutCoach2UserInput[]
  createMany?: Prisma.TournamentMatchCreateManyCoach2UserInputEnvelope
  set?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  disconnect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  delete?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  update?: Prisma.TournamentMatchUpdateWithWhereUniqueWithoutCoach2UserInput | Prisma.TournamentMatchUpdateWithWhereUniqueWithoutCoach2UserInput[]
  updateMany?: Prisma.TournamentMatchUpdateManyWithWhereWithoutCoach2UserInput | Prisma.TournamentMatchUpdateManyWithWhereWithoutCoach2UserInput[]
  deleteMany?: Prisma.TournamentMatchScalarWhereInput | Prisma.TournamentMatchScalarWhereInput[]
}

export type TournamentMatchUncheckedUpdateManyWithoutCoach1UserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach1UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput> | Prisma.TournamentMatchCreateWithoutCoach1UserInput[] | Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutCoach1UserInput | Prisma.TournamentMatchCreateOrConnectWithoutCoach1UserInput[]
  upsert?: Prisma.TournamentMatchUpsertWithWhereUniqueWithoutCoach1UserInput | Prisma.TournamentMatchUpsertWithWhereUniqueWithoutCoach1UserInput[]
  createMany?: Prisma.TournamentMatchCreateManyCoach1UserInputEnvelope
  set?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  disconnect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  delete?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  update?: Prisma.TournamentMatchUpdateWithWhereUniqueWithoutCoach1UserInput | Prisma.TournamentMatchUpdateWithWhereUniqueWithoutCoach1UserInput[]
  updateMany?: Prisma.TournamentMatchUpdateManyWithWhereWithoutCoach1UserInput | Prisma.TournamentMatchUpdateManyWithWhereWithoutCoach1UserInput[]
  deleteMany?: Prisma.TournamentMatchScalarWhereInput | Prisma.TournamentMatchScalarWhereInput[]
}

export type TournamentMatchCreateNestedManyWithoutRoundInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutRoundInput, Prisma.TournamentMatchUncheckedCreateWithoutRoundInput> | Prisma.TournamentMatchCreateWithoutRoundInput[] | Prisma.TournamentMatchUncheckedCreateWithoutRoundInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutRoundInput | Prisma.TournamentMatchCreateOrConnectWithoutRoundInput[]
  createMany?: Prisma.TournamentMatchCreateManyRoundInputEnvelope
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
}

export type TournamentMatchUncheckedCreateNestedManyWithoutRoundInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutRoundInput, Prisma.TournamentMatchUncheckedCreateWithoutRoundInput> | Prisma.TournamentMatchCreateWithoutRoundInput[] | Prisma.TournamentMatchUncheckedCreateWithoutRoundInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutRoundInput | Prisma.TournamentMatchCreateOrConnectWithoutRoundInput[]
  createMany?: Prisma.TournamentMatchCreateManyRoundInputEnvelope
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
}

export type TournamentMatchUpdateManyWithoutRoundNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutRoundInput, Prisma.TournamentMatchUncheckedCreateWithoutRoundInput> | Prisma.TournamentMatchCreateWithoutRoundInput[] | Prisma.TournamentMatchUncheckedCreateWithoutRoundInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutRoundInput | Prisma.TournamentMatchCreateOrConnectWithoutRoundInput[]
  upsert?: Prisma.TournamentMatchUpsertWithWhereUniqueWithoutRoundInput | Prisma.TournamentMatchUpsertWithWhereUniqueWithoutRoundInput[]
  createMany?: Prisma.TournamentMatchCreateManyRoundInputEnvelope
  set?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  disconnect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  delete?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  update?: Prisma.TournamentMatchUpdateWithWhereUniqueWithoutRoundInput | Prisma.TournamentMatchUpdateWithWhereUniqueWithoutRoundInput[]
  updateMany?: Prisma.TournamentMatchUpdateManyWithWhereWithoutRoundInput | Prisma.TournamentMatchUpdateManyWithWhereWithoutRoundInput[]
  deleteMany?: Prisma.TournamentMatchScalarWhereInput | Prisma.TournamentMatchScalarWhereInput[]
}

export type TournamentMatchUncheckedUpdateManyWithoutRoundNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentMatchCreateWithoutRoundInput, Prisma.TournamentMatchUncheckedCreateWithoutRoundInput> | Prisma.TournamentMatchCreateWithoutRoundInput[] | Prisma.TournamentMatchUncheckedCreateWithoutRoundInput[]
  connectOrCreate?: Prisma.TournamentMatchCreateOrConnectWithoutRoundInput | Prisma.TournamentMatchCreateOrConnectWithoutRoundInput[]
  upsert?: Prisma.TournamentMatchUpsertWithWhereUniqueWithoutRoundInput | Prisma.TournamentMatchUpsertWithWhereUniqueWithoutRoundInput[]
  createMany?: Prisma.TournamentMatchCreateManyRoundInputEnvelope
  set?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  disconnect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  delete?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  connect?: Prisma.TournamentMatchWhereUniqueInput | Prisma.TournamentMatchWhereUniqueInput[]
  update?: Prisma.TournamentMatchUpdateWithWhereUniqueWithoutRoundInput | Prisma.TournamentMatchUpdateWithWhereUniqueWithoutRoundInput[]
  updateMany?: Prisma.TournamentMatchUpdateManyWithWhereWithoutRoundInput | Prisma.TournamentMatchUpdateManyWithWhereWithoutRoundInput[]
  deleteMany?: Prisma.TournamentMatchScalarWhereInput | Prisma.TournamentMatchScalarWhereInput[]
}

export type TournamentMatchCreateWithoutCoach2UserInput = {
  id?: string
  tableNumber?: number | null
  coach1Name: string
  coach2Name: string
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  coach1User?: Prisma.UserCreateNestedOneWithoutMatchesAsCoach1Input
  round: Prisma.TournamentRoundCreateNestedOneWithoutMatchesInput
}

export type TournamentMatchUncheckedCreateWithoutCoach2UserInput = {
  id?: string
  roundId: string
  tableNumber?: number | null
  coach1Name: string
  coach1UserId?: string | null
  coach2Name: string
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentMatchCreateOrConnectWithoutCoach2UserInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach2UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput>
}

export type TournamentMatchCreateManyCoach2UserInputEnvelope = {
  data: Prisma.TournamentMatchCreateManyCoach2UserInput | Prisma.TournamentMatchCreateManyCoach2UserInput[]
}

export type TournamentMatchCreateWithoutCoach1UserInput = {
  id?: string
  tableNumber?: number | null
  coach1Name: string
  coach2Name: string
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  coach2User?: Prisma.UserCreateNestedOneWithoutMatchesAsCoach2Input
  round: Prisma.TournamentRoundCreateNestedOneWithoutMatchesInput
}

export type TournamentMatchUncheckedCreateWithoutCoach1UserInput = {
  id?: string
  roundId: string
  tableNumber?: number | null
  coach1Name: string
  coach2Name: string
  coach2UserId?: string | null
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentMatchCreateOrConnectWithoutCoach1UserInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach1UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput>
}

export type TournamentMatchCreateManyCoach1UserInputEnvelope = {
  data: Prisma.TournamentMatchCreateManyCoach1UserInput | Prisma.TournamentMatchCreateManyCoach1UserInput[]
}

export type TournamentMatchUpsertWithWhereUniqueWithoutCoach2UserInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentMatchUpdateWithoutCoach2UserInput, Prisma.TournamentMatchUncheckedUpdateWithoutCoach2UserInput>
  create: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach2UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach2UserInput>
}

export type TournamentMatchUpdateWithWhereUniqueWithoutCoach2UserInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentMatchUpdateWithoutCoach2UserInput, Prisma.TournamentMatchUncheckedUpdateWithoutCoach2UserInput>
}

export type TournamentMatchUpdateManyWithWhereWithoutCoach2UserInput = {
  where: Prisma.TournamentMatchScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentMatchUpdateManyMutationInput, Prisma.TournamentMatchUncheckedUpdateManyWithoutCoach2UserInput>
}

export type TournamentMatchScalarWhereInput = {
  AND?: Prisma.TournamentMatchScalarWhereInput | Prisma.TournamentMatchScalarWhereInput[]
  OR?: Prisma.TournamentMatchScalarWhereInput[]
  NOT?: Prisma.TournamentMatchScalarWhereInput | Prisma.TournamentMatchScalarWhereInput[]
  id?: Prisma.StringFilter<"TournamentMatch"> | string
  roundId?: Prisma.StringFilter<"TournamentMatch"> | string
  tableNumber?: Prisma.IntNullableFilter<"TournamentMatch"> | number | null
  coach1Name?: Prisma.StringFilter<"TournamentMatch"> | string
  coach1UserId?: Prisma.StringNullableFilter<"TournamentMatch"> | string | null
  coach2Name?: Prisma.StringFilter<"TournamentMatch"> | string
  coach2UserId?: Prisma.StringNullableFilter<"TournamentMatch"> | string | null
  coach1TD?: Prisma.IntFilter<"TournamentMatch"> | number
  coach1Casualties?: Prisma.IntFilter<"TournamentMatch"> | number
  coach2TD?: Prisma.IntFilter<"TournamentMatch"> | number
  coach2Casualties?: Prisma.IntFilter<"TournamentMatch"> | number
  createdAt?: Prisma.DateTimeFilter<"TournamentMatch"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentMatch"> | Date | string
}

export type TournamentMatchUpsertWithWhereUniqueWithoutCoach1UserInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentMatchUpdateWithoutCoach1UserInput, Prisma.TournamentMatchUncheckedUpdateWithoutCoach1UserInput>
  create: Prisma.XOR<Prisma.TournamentMatchCreateWithoutCoach1UserInput, Prisma.TournamentMatchUncheckedCreateWithoutCoach1UserInput>
}

export type TournamentMatchUpdateWithWhereUniqueWithoutCoach1UserInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentMatchUpdateWithoutCoach1UserInput, Prisma.TournamentMatchUncheckedUpdateWithoutCoach1UserInput>
}

export type TournamentMatchUpdateManyWithWhereWithoutCoach1UserInput = {
  where: Prisma.TournamentMatchScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentMatchUpdateManyMutationInput, Prisma.TournamentMatchUncheckedUpdateManyWithoutCoach1UserInput>
}

export type TournamentMatchCreateWithoutRoundInput = {
  id?: string
  tableNumber?: number | null
  coach1Name: string
  coach2Name: string
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  coach2User?: Prisma.UserCreateNestedOneWithoutMatchesAsCoach2Input
  coach1User?: Prisma.UserCreateNestedOneWithoutMatchesAsCoach1Input
}

export type TournamentMatchUncheckedCreateWithoutRoundInput = {
  id?: string
  tableNumber?: number | null
  coach1Name: string
  coach1UserId?: string | null
  coach2Name: string
  coach2UserId?: string | null
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentMatchCreateOrConnectWithoutRoundInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentMatchCreateWithoutRoundInput, Prisma.TournamentMatchUncheckedCreateWithoutRoundInput>
}

export type TournamentMatchCreateManyRoundInputEnvelope = {
  data: Prisma.TournamentMatchCreateManyRoundInput | Prisma.TournamentMatchCreateManyRoundInput[]
}

export type TournamentMatchUpsertWithWhereUniqueWithoutRoundInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentMatchUpdateWithoutRoundInput, Prisma.TournamentMatchUncheckedUpdateWithoutRoundInput>
  create: Prisma.XOR<Prisma.TournamentMatchCreateWithoutRoundInput, Prisma.TournamentMatchUncheckedCreateWithoutRoundInput>
}

export type TournamentMatchUpdateWithWhereUniqueWithoutRoundInput = {
  where: Prisma.TournamentMatchWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentMatchUpdateWithoutRoundInput, Prisma.TournamentMatchUncheckedUpdateWithoutRoundInput>
}

export type TournamentMatchUpdateManyWithWhereWithoutRoundInput = {
  where: Prisma.TournamentMatchScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentMatchUpdateManyMutationInput, Prisma.TournamentMatchUncheckedUpdateManyWithoutRoundInput>
}

export type TournamentMatchCreateManyCoach2UserInput = {
  id?: string
  roundId: string
  tableNumber?: number | null
  coach1Name: string
  coach1UserId?: string | null
  coach2Name: string
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentMatchCreateManyCoach1UserInput = {
  id?: string
  roundId: string
  tableNumber?: number | null
  coach1Name: string
  coach2Name: string
  coach2UserId?: string | null
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentMatchUpdateWithoutCoach2UserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coach1User?: Prisma.UserUpdateOneWithoutMatchesAsCoach1NestedInput
  round?: Prisma.TournamentRoundUpdateOneRequiredWithoutMatchesNestedInput
}

export type TournamentMatchUncheckedUpdateWithoutCoach2UserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentMatchUncheckedUpdateManyWithoutCoach2UserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentMatchUpdateWithoutCoach1UserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coach2User?: Prisma.UserUpdateOneWithoutMatchesAsCoach2NestedInput
  round?: Prisma.TournamentRoundUpdateOneRequiredWithoutMatchesNestedInput
}

export type TournamentMatchUncheckedUpdateWithoutCoach1UserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentMatchUncheckedUpdateManyWithoutCoach1UserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentMatchCreateManyRoundInput = {
  id?: string
  tableNumber?: number | null
  coach1Name: string
  coach1UserId?: string | null
  coach2Name: string
  coach2UserId?: string | null
  coach1TD?: number
  coach1Casualties?: number
  coach2TD?: number
  coach2Casualties?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentMatchUpdateWithoutRoundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coach2User?: Prisma.UserUpdateOneWithoutMatchesAsCoach2NestedInput
  coach1User?: Prisma.UserUpdateOneWithoutMatchesAsCoach1NestedInput
}

export type TournamentMatchUncheckedUpdateWithoutRoundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentMatchUncheckedUpdateManyWithoutRoundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coach1Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach1UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach2Name?: Prisma.StringFieldUpdateOperationsInput | string
  coach2UserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coach1TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach1Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  coach2TD?: Prisma.IntFieldUpdateOperationsInput | number
  coach2Casualties?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TournamentMatchSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roundId?: boolean
  tableNumber?: boolean
  coach1Name?: boolean
  coach1UserId?: boolean
  coach2Name?: boolean
  coach2UserId?: boolean
  coach1TD?: boolean
  coach1Casualties?: boolean
  coach2TD?: boolean
  coach2Casualties?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  coach2User?: boolean | Prisma.TournamentMatch$coach2UserArgs<ExtArgs>
  coach1User?: boolean | Prisma.TournamentMatch$coach1UserArgs<ExtArgs>
  round?: boolean | Prisma.TournamentRoundDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentMatch"]>

export type TournamentMatchSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roundId?: boolean
  tableNumber?: boolean
  coach1Name?: boolean
  coach1UserId?: boolean
  coach2Name?: boolean
  coach2UserId?: boolean
  coach1TD?: boolean
  coach1Casualties?: boolean
  coach2TD?: boolean
  coach2Casualties?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  coach2User?: boolean | Prisma.TournamentMatch$coach2UserArgs<ExtArgs>
  coach1User?: boolean | Prisma.TournamentMatch$coach1UserArgs<ExtArgs>
  round?: boolean | Prisma.TournamentRoundDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentMatch"]>

export type TournamentMatchSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roundId?: boolean
  tableNumber?: boolean
  coach1Name?: boolean
  coach1UserId?: boolean
  coach2Name?: boolean
  coach2UserId?: boolean
  coach1TD?: boolean
  coach1Casualties?: boolean
  coach2TD?: boolean
  coach2Casualties?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  coach2User?: boolean | Prisma.TournamentMatch$coach2UserArgs<ExtArgs>
  coach1User?: boolean | Prisma.TournamentMatch$coach1UserArgs<ExtArgs>
  round?: boolean | Prisma.TournamentRoundDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentMatch"]>

export type TournamentMatchSelectScalar = {
  id?: boolean
  roundId?: boolean
  tableNumber?: boolean
  coach1Name?: boolean
  coach1UserId?: boolean
  coach2Name?: boolean
  coach2UserId?: boolean
  coach1TD?: boolean
  coach1Casualties?: boolean
  coach2TD?: boolean
  coach2Casualties?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TournamentMatchOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "roundId" | "tableNumber" | "coach1Name" | "coach1UserId" | "coach2Name" | "coach2UserId" | "coach1TD" | "coach1Casualties" | "coach2TD" | "coach2Casualties" | "createdAt" | "updatedAt", ExtArgs["result"]["tournamentMatch"]>
export type TournamentMatchInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coach2User?: boolean | Prisma.TournamentMatch$coach2UserArgs<ExtArgs>
  coach1User?: boolean | Prisma.TournamentMatch$coach1UserArgs<ExtArgs>
  round?: boolean | Prisma.TournamentRoundDefaultArgs<ExtArgs>
}
export type TournamentMatchIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coach2User?: boolean | Prisma.TournamentMatch$coach2UserArgs<ExtArgs>
  coach1User?: boolean | Prisma.TournamentMatch$coach1UserArgs<ExtArgs>
  round?: boolean | Prisma.TournamentRoundDefaultArgs<ExtArgs>
}
export type TournamentMatchIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coach2User?: boolean | Prisma.TournamentMatch$coach2UserArgs<ExtArgs>
  coach1User?: boolean | Prisma.TournamentMatch$coach1UserArgs<ExtArgs>
  round?: boolean | Prisma.TournamentRoundDefaultArgs<ExtArgs>
}

export type $TournamentMatchPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TournamentMatch"
  objects: {
    coach2User: Prisma.$UserPayload<ExtArgs> | null
    coach1User: Prisma.$UserPayload<ExtArgs> | null
    round: Prisma.$TournamentRoundPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    roundId: string
    tableNumber: number | null
    coach1Name: string
    coach1UserId: string | null
    coach2Name: string
    coach2UserId: string | null
    coach1TD: number
    coach1Casualties: number
    coach2TD: number
    coach2Casualties: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tournamentMatch"]>
  composites: {}
}

export type TournamentMatchGetPayload<S extends boolean | null | undefined | TournamentMatchDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload, S>

export type TournamentMatchCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TournamentMatchFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TournamentMatchCountAggregateInputType | true
  }

export interface TournamentMatchDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TournamentMatch'], meta: { name: 'TournamentMatch' } }
  /**
   * Find zero or one TournamentMatch that matches the filter.
   * @param {TournamentMatchFindUniqueArgs} args - Arguments to find a TournamentMatch
   * @example
   * // Get one TournamentMatch
   * const tournamentMatch = await prisma.tournamentMatch.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TournamentMatchFindUniqueArgs>(args: Prisma.SelectSubset<T, TournamentMatchFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TournamentMatchClient<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TournamentMatch that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TournamentMatchFindUniqueOrThrowArgs} args - Arguments to find a TournamentMatch
   * @example
   * // Get one TournamentMatch
   * const tournamentMatch = await prisma.tournamentMatch.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TournamentMatchFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TournamentMatchFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentMatchClient<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentMatch that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentMatchFindFirstArgs} args - Arguments to find a TournamentMatch
   * @example
   * // Get one TournamentMatch
   * const tournamentMatch = await prisma.tournamentMatch.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TournamentMatchFindFirstArgs>(args?: Prisma.SelectSubset<T, TournamentMatchFindFirstArgs<ExtArgs>>): Prisma.Prisma__TournamentMatchClient<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentMatch that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentMatchFindFirstOrThrowArgs} args - Arguments to find a TournamentMatch
   * @example
   * // Get one TournamentMatch
   * const tournamentMatch = await prisma.tournamentMatch.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TournamentMatchFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TournamentMatchFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentMatchClient<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TournamentMatches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentMatchFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TournamentMatches
   * const tournamentMatches = await prisma.tournamentMatch.findMany()
   * 
   * // Get first 10 TournamentMatches
   * const tournamentMatches = await prisma.tournamentMatch.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tournamentMatchWithIdOnly = await prisma.tournamentMatch.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TournamentMatchFindManyArgs>(args?: Prisma.SelectSubset<T, TournamentMatchFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TournamentMatch.
   * @param {TournamentMatchCreateArgs} args - Arguments to create a TournamentMatch.
   * @example
   * // Create one TournamentMatch
   * const TournamentMatch = await prisma.tournamentMatch.create({
   *   data: {
   *     // ... data to create a TournamentMatch
   *   }
   * })
   * 
   */
  create<T extends TournamentMatchCreateArgs>(args: Prisma.SelectSubset<T, TournamentMatchCreateArgs<ExtArgs>>): Prisma.Prisma__TournamentMatchClient<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TournamentMatches.
   * @param {TournamentMatchCreateManyArgs} args - Arguments to create many TournamentMatches.
   * @example
   * // Create many TournamentMatches
   * const tournamentMatch = await prisma.tournamentMatch.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TournamentMatchCreateManyArgs>(args?: Prisma.SelectSubset<T, TournamentMatchCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TournamentMatches and returns the data saved in the database.
   * @param {TournamentMatchCreateManyAndReturnArgs} args - Arguments to create many TournamentMatches.
   * @example
   * // Create many TournamentMatches
   * const tournamentMatch = await prisma.tournamentMatch.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TournamentMatches and only return the `id`
   * const tournamentMatchWithIdOnly = await prisma.tournamentMatch.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TournamentMatchCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TournamentMatchCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TournamentMatch.
   * @param {TournamentMatchDeleteArgs} args - Arguments to delete one TournamentMatch.
   * @example
   * // Delete one TournamentMatch
   * const TournamentMatch = await prisma.tournamentMatch.delete({
   *   where: {
   *     // ... filter to delete one TournamentMatch
   *   }
   * })
   * 
   */
  delete<T extends TournamentMatchDeleteArgs>(args: Prisma.SelectSubset<T, TournamentMatchDeleteArgs<ExtArgs>>): Prisma.Prisma__TournamentMatchClient<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TournamentMatch.
   * @param {TournamentMatchUpdateArgs} args - Arguments to update one TournamentMatch.
   * @example
   * // Update one TournamentMatch
   * const tournamentMatch = await prisma.tournamentMatch.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TournamentMatchUpdateArgs>(args: Prisma.SelectSubset<T, TournamentMatchUpdateArgs<ExtArgs>>): Prisma.Prisma__TournamentMatchClient<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TournamentMatches.
   * @param {TournamentMatchDeleteManyArgs} args - Arguments to filter TournamentMatches to delete.
   * @example
   * // Delete a few TournamentMatches
   * const { count } = await prisma.tournamentMatch.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TournamentMatchDeleteManyArgs>(args?: Prisma.SelectSubset<T, TournamentMatchDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentMatches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentMatchUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TournamentMatches
   * const tournamentMatch = await prisma.tournamentMatch.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TournamentMatchUpdateManyArgs>(args: Prisma.SelectSubset<T, TournamentMatchUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentMatches and returns the data updated in the database.
   * @param {TournamentMatchUpdateManyAndReturnArgs} args - Arguments to update many TournamentMatches.
   * @example
   * // Update many TournamentMatches
   * const tournamentMatch = await prisma.tournamentMatch.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TournamentMatches and only return the `id`
   * const tournamentMatchWithIdOnly = await prisma.tournamentMatch.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TournamentMatchUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TournamentMatchUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TournamentMatch.
   * @param {TournamentMatchUpsertArgs} args - Arguments to update or create a TournamentMatch.
   * @example
   * // Update or create a TournamentMatch
   * const tournamentMatch = await prisma.tournamentMatch.upsert({
   *   create: {
   *     // ... data to create a TournamentMatch
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TournamentMatch we want to update
   *   }
   * })
   */
  upsert<T extends TournamentMatchUpsertArgs>(args: Prisma.SelectSubset<T, TournamentMatchUpsertArgs<ExtArgs>>): Prisma.Prisma__TournamentMatchClient<runtime.Types.Result.GetResult<Prisma.$TournamentMatchPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TournamentMatches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentMatchCountArgs} args - Arguments to filter TournamentMatches to count.
   * @example
   * // Count the number of TournamentMatches
   * const count = await prisma.tournamentMatch.count({
   *   where: {
   *     // ... the filter for the TournamentMatches we want to count
   *   }
   * })
  **/
  count<T extends TournamentMatchCountArgs>(
    args?: Prisma.Subset<T, TournamentMatchCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TournamentMatchCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TournamentMatch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentMatchAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TournamentMatchAggregateArgs>(args: Prisma.Subset<T, TournamentMatchAggregateArgs>): Prisma.PrismaPromise<GetTournamentMatchAggregateType<T>>

  /**
   * Group by TournamentMatch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentMatchGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TournamentMatchGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TournamentMatchGroupByArgs['orderBy'] }
      : { orderBy?: TournamentMatchGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TournamentMatchGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTournamentMatchGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TournamentMatch model
 */
readonly fields: TournamentMatchFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TournamentMatch.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TournamentMatchClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  coach2User<T extends Prisma.TournamentMatch$coach2UserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentMatch$coach2UserArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  coach1User<T extends Prisma.TournamentMatch$coach1UserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentMatch$coach1UserArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  round<T extends Prisma.TournamentRoundDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentRoundDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentRoundClient<runtime.Types.Result.GetResult<Prisma.$TournamentRoundPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TournamentMatch model
 */
export interface TournamentMatchFieldRefs {
  readonly id: Prisma.FieldRef<"TournamentMatch", 'String'>
  readonly roundId: Prisma.FieldRef<"TournamentMatch", 'String'>
  readonly tableNumber: Prisma.FieldRef<"TournamentMatch", 'Int'>
  readonly coach1Name: Prisma.FieldRef<"TournamentMatch", 'String'>
  readonly coach1UserId: Prisma.FieldRef<"TournamentMatch", 'String'>
  readonly coach2Name: Prisma.FieldRef<"TournamentMatch", 'String'>
  readonly coach2UserId: Prisma.FieldRef<"TournamentMatch", 'String'>
  readonly coach1TD: Prisma.FieldRef<"TournamentMatch", 'Int'>
  readonly coach1Casualties: Prisma.FieldRef<"TournamentMatch", 'Int'>
  readonly coach2TD: Prisma.FieldRef<"TournamentMatch", 'Int'>
  readonly coach2Casualties: Prisma.FieldRef<"TournamentMatch", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TournamentMatch", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TournamentMatch", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TournamentMatch findUnique
 */
export type TournamentMatchFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * Filter, which TournamentMatch to fetch.
   */
  where: Prisma.TournamentMatchWhereUniqueInput
}

/**
 * TournamentMatch findUniqueOrThrow
 */
export type TournamentMatchFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * Filter, which TournamentMatch to fetch.
   */
  where: Prisma.TournamentMatchWhereUniqueInput
}

/**
 * TournamentMatch findFirst
 */
export type TournamentMatchFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * Filter, which TournamentMatch to fetch.
   */
  where?: Prisma.TournamentMatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentMatches to fetch.
   */
  orderBy?: Prisma.TournamentMatchOrderByWithRelationInput | Prisma.TournamentMatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentMatches.
   */
  cursor?: Prisma.TournamentMatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentMatches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentMatches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentMatches.
   */
  distinct?: Prisma.TournamentMatchScalarFieldEnum | Prisma.TournamentMatchScalarFieldEnum[]
}

/**
 * TournamentMatch findFirstOrThrow
 */
export type TournamentMatchFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * Filter, which TournamentMatch to fetch.
   */
  where?: Prisma.TournamentMatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentMatches to fetch.
   */
  orderBy?: Prisma.TournamentMatchOrderByWithRelationInput | Prisma.TournamentMatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentMatches.
   */
  cursor?: Prisma.TournamentMatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentMatches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentMatches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentMatches.
   */
  distinct?: Prisma.TournamentMatchScalarFieldEnum | Prisma.TournamentMatchScalarFieldEnum[]
}

/**
 * TournamentMatch findMany
 */
export type TournamentMatchFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * Filter, which TournamentMatches to fetch.
   */
  where?: Prisma.TournamentMatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentMatches to fetch.
   */
  orderBy?: Prisma.TournamentMatchOrderByWithRelationInput | Prisma.TournamentMatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TournamentMatches.
   */
  cursor?: Prisma.TournamentMatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentMatches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentMatches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentMatches.
   */
  distinct?: Prisma.TournamentMatchScalarFieldEnum | Prisma.TournamentMatchScalarFieldEnum[]
}

/**
 * TournamentMatch create
 */
export type TournamentMatchCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * The data needed to create a TournamentMatch.
   */
  data: Prisma.XOR<Prisma.TournamentMatchCreateInput, Prisma.TournamentMatchUncheckedCreateInput>
}

/**
 * TournamentMatch createMany
 */
export type TournamentMatchCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TournamentMatches.
   */
  data: Prisma.TournamentMatchCreateManyInput | Prisma.TournamentMatchCreateManyInput[]
}

/**
 * TournamentMatch createManyAndReturn
 */
export type TournamentMatchCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * The data used to create many TournamentMatches.
   */
  data: Prisma.TournamentMatchCreateManyInput | Prisma.TournamentMatchCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentMatch update
 */
export type TournamentMatchUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * The data needed to update a TournamentMatch.
   */
  data: Prisma.XOR<Prisma.TournamentMatchUpdateInput, Prisma.TournamentMatchUncheckedUpdateInput>
  /**
   * Choose, which TournamentMatch to update.
   */
  where: Prisma.TournamentMatchWhereUniqueInput
}

/**
 * TournamentMatch updateMany
 */
export type TournamentMatchUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TournamentMatches.
   */
  data: Prisma.XOR<Prisma.TournamentMatchUpdateManyMutationInput, Prisma.TournamentMatchUncheckedUpdateManyInput>
  /**
   * Filter which TournamentMatches to update
   */
  where?: Prisma.TournamentMatchWhereInput
  /**
   * Limit how many TournamentMatches to update.
   */
  limit?: number
}

/**
 * TournamentMatch updateManyAndReturn
 */
export type TournamentMatchUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * The data used to update TournamentMatches.
   */
  data: Prisma.XOR<Prisma.TournamentMatchUpdateManyMutationInput, Prisma.TournamentMatchUncheckedUpdateManyInput>
  /**
   * Filter which TournamentMatches to update
   */
  where?: Prisma.TournamentMatchWhereInput
  /**
   * Limit how many TournamentMatches to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentMatch upsert
 */
export type TournamentMatchUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * The filter to search for the TournamentMatch to update in case it exists.
   */
  where: Prisma.TournamentMatchWhereUniqueInput
  /**
   * In case the TournamentMatch found by the `where` argument doesn't exist, create a new TournamentMatch with this data.
   */
  create: Prisma.XOR<Prisma.TournamentMatchCreateInput, Prisma.TournamentMatchUncheckedCreateInput>
  /**
   * In case the TournamentMatch was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TournamentMatchUpdateInput, Prisma.TournamentMatchUncheckedUpdateInput>
}

/**
 * TournamentMatch delete
 */
export type TournamentMatchDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
  /**
   * Filter which TournamentMatch to delete.
   */
  where: Prisma.TournamentMatchWhereUniqueInput
}

/**
 * TournamentMatch deleteMany
 */
export type TournamentMatchDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentMatches to delete
   */
  where?: Prisma.TournamentMatchWhereInput
  /**
   * Limit how many TournamentMatches to delete.
   */
  limit?: number
}

/**
 * TournamentMatch.coach2User
 */
export type TournamentMatch$coach2UserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * TournamentMatch.coach1User
 */
export type TournamentMatch$coach1UserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * TournamentMatch without action
 */
export type TournamentMatchDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentMatch
   */
  select?: Prisma.TournamentMatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentMatch
   */
  omit?: Prisma.TournamentMatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentMatchInclude<ExtArgs> | null
}
