
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TournamentTeamMember` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TournamentTeamMember
 * 
 */
export type TournamentTeamMemberModel = runtime.Types.Result.DefaultSelection<Prisma.$TournamentTeamMemberPayload>

export type AggregateTournamentTeamMember = {
  _count: TournamentTeamMemberCountAggregateOutputType | null
  _min: TournamentTeamMemberMinAggregateOutputType | null
  _max: TournamentTeamMemberMaxAggregateOutputType | null
}

export type TournamentTeamMemberMinAggregateOutputType = {
  id: string | null
  teamId: string | null
  userId: string | null
}

export type TournamentTeamMemberMaxAggregateOutputType = {
  id: string | null
  teamId: string | null
  userId: string | null
}

export type TournamentTeamMemberCountAggregateOutputType = {
  id: number
  teamId: number
  userId: number
  _all: number
}


export type TournamentTeamMemberMinAggregateInputType = {
  id?: true
  teamId?: true
  userId?: true
}

export type TournamentTeamMemberMaxAggregateInputType = {
  id?: true
  teamId?: true
  userId?: true
}

export type TournamentTeamMemberCountAggregateInputType = {
  id?: true
  teamId?: true
  userId?: true
  _all?: true
}

export type TournamentTeamMemberAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentTeamMember to aggregate.
   */
  where?: Prisma.TournamentTeamMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentTeamMembers to fetch.
   */
  orderBy?: Prisma.TournamentTeamMemberOrderByWithRelationInput | Prisma.TournamentTeamMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TournamentTeamMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentTeamMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentTeamMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TournamentTeamMembers
  **/
  _count?: true | TournamentTeamMemberCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TournamentTeamMemberMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TournamentTeamMemberMaxAggregateInputType
}

export type GetTournamentTeamMemberAggregateType<T extends TournamentTeamMemberAggregateArgs> = {
      [P in keyof T & keyof AggregateTournamentTeamMember]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTournamentTeamMember[P]>
    : Prisma.GetScalarType<T[P], AggregateTournamentTeamMember[P]>
}




export type TournamentTeamMemberGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TournamentTeamMemberWhereInput
  orderBy?: Prisma.TournamentTeamMemberOrderByWithAggregationInput | Prisma.TournamentTeamMemberOrderByWithAggregationInput[]
  by: Prisma.TournamentTeamMemberScalarFieldEnum[] | Prisma.TournamentTeamMemberScalarFieldEnum
  having?: Prisma.TournamentTeamMemberScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TournamentTeamMemberCountAggregateInputType | true
  _min?: TournamentTeamMemberMinAggregateInputType
  _max?: TournamentTeamMemberMaxAggregateInputType
}

export type TournamentTeamMemberGroupByOutputType = {
  id: string
  teamId: string
  userId: string
  _count: TournamentTeamMemberCountAggregateOutputType | null
  _min: TournamentTeamMemberMinAggregateOutputType | null
  _max: TournamentTeamMemberMaxAggregateOutputType | null
}

type GetTournamentTeamMemberGroupByPayload<T extends TournamentTeamMemberGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TournamentTeamMemberGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TournamentTeamMemberGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TournamentTeamMemberGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TournamentTeamMemberGroupByOutputType[P]>
      }
    >
  >



export type TournamentTeamMemberWhereInput = {
  AND?: Prisma.TournamentTeamMemberWhereInput | Prisma.TournamentTeamMemberWhereInput[]
  OR?: Prisma.TournamentTeamMemberWhereInput[]
  NOT?: Prisma.TournamentTeamMemberWhereInput | Prisma.TournamentTeamMemberWhereInput[]
  id?: Prisma.StringFilter<"TournamentTeamMember"> | string
  teamId?: Prisma.StringFilter<"TournamentTeamMember"> | string
  userId?: Prisma.StringFilter<"TournamentTeamMember"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  team?: Prisma.XOR<Prisma.TournamentTeamScalarRelationFilter, Prisma.TournamentTeamWhereInput>
}

export type TournamentTeamMemberOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  team?: Prisma.TournamentTeamOrderByWithRelationInput
}

export type TournamentTeamMemberWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  teamId_userId?: Prisma.TournamentTeamMemberTeamIdUserIdCompoundUniqueInput
  AND?: Prisma.TournamentTeamMemberWhereInput | Prisma.TournamentTeamMemberWhereInput[]
  OR?: Prisma.TournamentTeamMemberWhereInput[]
  NOT?: Prisma.TournamentTeamMemberWhereInput | Prisma.TournamentTeamMemberWhereInput[]
  teamId?: Prisma.StringFilter<"TournamentTeamMember"> | string
  userId?: Prisma.StringFilter<"TournamentTeamMember"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  team?: Prisma.XOR<Prisma.TournamentTeamScalarRelationFilter, Prisma.TournamentTeamWhereInput>
}, "id" | "teamId_userId">

export type TournamentTeamMemberOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.TournamentTeamMemberCountOrderByAggregateInput
  _max?: Prisma.TournamentTeamMemberMaxOrderByAggregateInput
  _min?: Prisma.TournamentTeamMemberMinOrderByAggregateInput
}

export type TournamentTeamMemberScalarWhereWithAggregatesInput = {
  AND?: Prisma.TournamentTeamMemberScalarWhereWithAggregatesInput | Prisma.TournamentTeamMemberScalarWhereWithAggregatesInput[]
  OR?: Prisma.TournamentTeamMemberScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TournamentTeamMemberScalarWhereWithAggregatesInput | Prisma.TournamentTeamMemberScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TournamentTeamMember"> | string
  teamId?: Prisma.StringWithAggregatesFilter<"TournamentTeamMember"> | string
  userId?: Prisma.StringWithAggregatesFilter<"TournamentTeamMember"> | string
}

export type TournamentTeamMemberCreateInput = {
  id?: string
  user: Prisma.UserCreateNestedOneWithoutTeamMembershipsInput
  team: Prisma.TournamentTeamCreateNestedOneWithoutMembersInput
}

export type TournamentTeamMemberUncheckedCreateInput = {
  id?: string
  teamId: string
  userId: string
}

export type TournamentTeamMemberUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutTeamMembershipsNestedInput
  team?: Prisma.TournamentTeamUpdateOneRequiredWithoutMembersNestedInput
}

export type TournamentTeamMemberUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TournamentTeamMemberCreateManyInput = {
  id?: string
  teamId: string
  userId: string
}

export type TournamentTeamMemberUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TournamentTeamMemberUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TournamentTeamMemberListRelationFilter = {
  every?: Prisma.TournamentTeamMemberWhereInput
  some?: Prisma.TournamentTeamMemberWhereInput
  none?: Prisma.TournamentTeamMemberWhereInput
}

export type TournamentTeamMemberOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TournamentTeamMemberTeamIdUserIdCompoundUniqueInput = {
  teamId: string
  userId: string
}

export type TournamentTeamMemberCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TournamentTeamMemberMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TournamentTeamMemberMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TournamentTeamMemberCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutUserInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput> | Prisma.TournamentTeamMemberCreateWithoutUserInput[] | Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentTeamMemberCreateOrConnectWithoutUserInput | Prisma.TournamentTeamMemberCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TournamentTeamMemberCreateManyUserInputEnvelope
  connect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
}

export type TournamentTeamMemberUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutUserInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput> | Prisma.TournamentTeamMemberCreateWithoutUserInput[] | Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentTeamMemberCreateOrConnectWithoutUserInput | Prisma.TournamentTeamMemberCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TournamentTeamMemberCreateManyUserInputEnvelope
  connect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
}

export type TournamentTeamMemberUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutUserInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput> | Prisma.TournamentTeamMemberCreateWithoutUserInput[] | Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentTeamMemberCreateOrConnectWithoutUserInput | Prisma.TournamentTeamMemberCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TournamentTeamMemberUpsertWithWhereUniqueWithoutUserInput | Prisma.TournamentTeamMemberUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TournamentTeamMemberCreateManyUserInputEnvelope
  set?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  disconnect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  delete?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  connect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  update?: Prisma.TournamentTeamMemberUpdateWithWhereUniqueWithoutUserInput | Prisma.TournamentTeamMemberUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TournamentTeamMemberUpdateManyWithWhereWithoutUserInput | Prisma.TournamentTeamMemberUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TournamentTeamMemberScalarWhereInput | Prisma.TournamentTeamMemberScalarWhereInput[]
}

export type TournamentTeamMemberUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutUserInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput> | Prisma.TournamentTeamMemberCreateWithoutUserInput[] | Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentTeamMemberCreateOrConnectWithoutUserInput | Prisma.TournamentTeamMemberCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TournamentTeamMemberUpsertWithWhereUniqueWithoutUserInput | Prisma.TournamentTeamMemberUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TournamentTeamMemberCreateManyUserInputEnvelope
  set?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  disconnect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  delete?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  connect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  update?: Prisma.TournamentTeamMemberUpdateWithWhereUniqueWithoutUserInput | Prisma.TournamentTeamMemberUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TournamentTeamMemberUpdateManyWithWhereWithoutUserInput | Prisma.TournamentTeamMemberUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TournamentTeamMemberScalarWhereInput | Prisma.TournamentTeamMemberScalarWhereInput[]
}

export type TournamentTeamMemberCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutTeamInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput> | Prisma.TournamentTeamMemberCreateWithoutTeamInput[] | Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TournamentTeamMemberCreateOrConnectWithoutTeamInput | Prisma.TournamentTeamMemberCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.TournamentTeamMemberCreateManyTeamInputEnvelope
  connect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
}

export type TournamentTeamMemberUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutTeamInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput> | Prisma.TournamentTeamMemberCreateWithoutTeamInput[] | Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TournamentTeamMemberCreateOrConnectWithoutTeamInput | Prisma.TournamentTeamMemberCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.TournamentTeamMemberCreateManyTeamInputEnvelope
  connect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
}

export type TournamentTeamMemberUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutTeamInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput> | Prisma.TournamentTeamMemberCreateWithoutTeamInput[] | Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TournamentTeamMemberCreateOrConnectWithoutTeamInput | Prisma.TournamentTeamMemberCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.TournamentTeamMemberUpsertWithWhereUniqueWithoutTeamInput | Prisma.TournamentTeamMemberUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.TournamentTeamMemberCreateManyTeamInputEnvelope
  set?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  disconnect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  delete?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  connect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  update?: Prisma.TournamentTeamMemberUpdateWithWhereUniqueWithoutTeamInput | Prisma.TournamentTeamMemberUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.TournamentTeamMemberUpdateManyWithWhereWithoutTeamInput | Prisma.TournamentTeamMemberUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.TournamentTeamMemberScalarWhereInput | Prisma.TournamentTeamMemberScalarWhereInput[]
}

export type TournamentTeamMemberUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutTeamInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput> | Prisma.TournamentTeamMemberCreateWithoutTeamInput[] | Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TournamentTeamMemberCreateOrConnectWithoutTeamInput | Prisma.TournamentTeamMemberCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.TournamentTeamMemberUpsertWithWhereUniqueWithoutTeamInput | Prisma.TournamentTeamMemberUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.TournamentTeamMemberCreateManyTeamInputEnvelope
  set?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  disconnect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  delete?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  connect?: Prisma.TournamentTeamMemberWhereUniqueInput | Prisma.TournamentTeamMemberWhereUniqueInput[]
  update?: Prisma.TournamentTeamMemberUpdateWithWhereUniqueWithoutTeamInput | Prisma.TournamentTeamMemberUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.TournamentTeamMemberUpdateManyWithWhereWithoutTeamInput | Prisma.TournamentTeamMemberUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.TournamentTeamMemberScalarWhereInput | Prisma.TournamentTeamMemberScalarWhereInput[]
}

export type TournamentTeamMemberCreateWithoutUserInput = {
  id?: string
  team: Prisma.TournamentTeamCreateNestedOneWithoutMembersInput
}

export type TournamentTeamMemberUncheckedCreateWithoutUserInput = {
  id?: string
  teamId: string
}

export type TournamentTeamMemberCreateOrConnectWithoutUserInput = {
  where: Prisma.TournamentTeamMemberWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutUserInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput>
}

export type TournamentTeamMemberCreateManyUserInputEnvelope = {
  data: Prisma.TournamentTeamMemberCreateManyUserInput | Prisma.TournamentTeamMemberCreateManyUserInput[]
}

export type TournamentTeamMemberUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TournamentTeamMemberWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentTeamMemberUpdateWithoutUserInput, Prisma.TournamentTeamMemberUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutUserInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutUserInput>
}

export type TournamentTeamMemberUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TournamentTeamMemberWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentTeamMemberUpdateWithoutUserInput, Prisma.TournamentTeamMemberUncheckedUpdateWithoutUserInput>
}

export type TournamentTeamMemberUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TournamentTeamMemberScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentTeamMemberUpdateManyMutationInput, Prisma.TournamentTeamMemberUncheckedUpdateManyWithoutUserInput>
}

export type TournamentTeamMemberScalarWhereInput = {
  AND?: Prisma.TournamentTeamMemberScalarWhereInput | Prisma.TournamentTeamMemberScalarWhereInput[]
  OR?: Prisma.TournamentTeamMemberScalarWhereInput[]
  NOT?: Prisma.TournamentTeamMemberScalarWhereInput | Prisma.TournamentTeamMemberScalarWhereInput[]
  id?: Prisma.StringFilter<"TournamentTeamMember"> | string
  teamId?: Prisma.StringFilter<"TournamentTeamMember"> | string
  userId?: Prisma.StringFilter<"TournamentTeamMember"> | string
}

export type TournamentTeamMemberCreateWithoutTeamInput = {
  id?: string
  user: Prisma.UserCreateNestedOneWithoutTeamMembershipsInput
}

export type TournamentTeamMemberUncheckedCreateWithoutTeamInput = {
  id?: string
  userId: string
}

export type TournamentTeamMemberCreateOrConnectWithoutTeamInput = {
  where: Prisma.TournamentTeamMemberWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutTeamInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput>
}

export type TournamentTeamMemberCreateManyTeamInputEnvelope = {
  data: Prisma.TournamentTeamMemberCreateManyTeamInput | Prisma.TournamentTeamMemberCreateManyTeamInput[]
}

export type TournamentTeamMemberUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.TournamentTeamMemberWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentTeamMemberUpdateWithoutTeamInput, Prisma.TournamentTeamMemberUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.TournamentTeamMemberCreateWithoutTeamInput, Prisma.TournamentTeamMemberUncheckedCreateWithoutTeamInput>
}

export type TournamentTeamMemberUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.TournamentTeamMemberWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentTeamMemberUpdateWithoutTeamInput, Prisma.TournamentTeamMemberUncheckedUpdateWithoutTeamInput>
}

export type TournamentTeamMemberUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.TournamentTeamMemberScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentTeamMemberUpdateManyMutationInput, Prisma.TournamentTeamMemberUncheckedUpdateManyWithoutTeamInput>
}

export type TournamentTeamMemberCreateManyUserInput = {
  id?: string
  teamId: string
}

export type TournamentTeamMemberUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.TournamentTeamUpdateOneRequiredWithoutMembersNestedInput
}

export type TournamentTeamMemberUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TournamentTeamMemberUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TournamentTeamMemberCreateManyTeamInput = {
  id?: string
  userId: string
}

export type TournamentTeamMemberUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutTeamMembershipsNestedInput
}

export type TournamentTeamMemberUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TournamentTeamMemberUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TournamentTeamMemberSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TournamentTeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentTeamMember"]>

export type TournamentTeamMemberSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TournamentTeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentTeamMember"]>

export type TournamentTeamMemberSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TournamentTeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentTeamMember"]>

export type TournamentTeamMemberSelectScalar = {
  id?: boolean
  teamId?: boolean
  userId?: boolean
}

export type TournamentTeamMemberOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "teamId" | "userId", ExtArgs["result"]["tournamentTeamMember"]>
export type TournamentTeamMemberInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TournamentTeamDefaultArgs<ExtArgs>
}
export type TournamentTeamMemberIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TournamentTeamDefaultArgs<ExtArgs>
}
export type TournamentTeamMemberIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TournamentTeamDefaultArgs<ExtArgs>
}

export type $TournamentTeamMemberPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TournamentTeamMember"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    team: Prisma.$TournamentTeamPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    teamId: string
    userId: string
  }, ExtArgs["result"]["tournamentTeamMember"]>
  composites: {}
}

export type TournamentTeamMemberGetPayload<S extends boolean | null | undefined | TournamentTeamMemberDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload, S>

export type TournamentTeamMemberCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TournamentTeamMemberFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TournamentTeamMemberCountAggregateInputType | true
  }

export interface TournamentTeamMemberDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TournamentTeamMember'], meta: { name: 'TournamentTeamMember' } }
  /**
   * Find zero or one TournamentTeamMember that matches the filter.
   * @param {TournamentTeamMemberFindUniqueArgs} args - Arguments to find a TournamentTeamMember
   * @example
   * // Get one TournamentTeamMember
   * const tournamentTeamMember = await prisma.tournamentTeamMember.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TournamentTeamMemberFindUniqueArgs>(args: Prisma.SelectSubset<T, TournamentTeamMemberFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamMemberClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TournamentTeamMember that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TournamentTeamMemberFindUniqueOrThrowArgs} args - Arguments to find a TournamentTeamMember
   * @example
   * // Get one TournamentTeamMember
   * const tournamentTeamMember = await prisma.tournamentTeamMember.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TournamentTeamMemberFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TournamentTeamMemberFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamMemberClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentTeamMember that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentTeamMemberFindFirstArgs} args - Arguments to find a TournamentTeamMember
   * @example
   * // Get one TournamentTeamMember
   * const tournamentTeamMember = await prisma.tournamentTeamMember.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TournamentTeamMemberFindFirstArgs>(args?: Prisma.SelectSubset<T, TournamentTeamMemberFindFirstArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamMemberClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentTeamMember that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentTeamMemberFindFirstOrThrowArgs} args - Arguments to find a TournamentTeamMember
   * @example
   * // Get one TournamentTeamMember
   * const tournamentTeamMember = await prisma.tournamentTeamMember.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TournamentTeamMemberFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TournamentTeamMemberFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamMemberClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TournamentTeamMembers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentTeamMemberFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TournamentTeamMembers
   * const tournamentTeamMembers = await prisma.tournamentTeamMember.findMany()
   * 
   * // Get first 10 TournamentTeamMembers
   * const tournamentTeamMembers = await prisma.tournamentTeamMember.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tournamentTeamMemberWithIdOnly = await prisma.tournamentTeamMember.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TournamentTeamMemberFindManyArgs>(args?: Prisma.SelectSubset<T, TournamentTeamMemberFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TournamentTeamMember.
   * @param {TournamentTeamMemberCreateArgs} args - Arguments to create a TournamentTeamMember.
   * @example
   * // Create one TournamentTeamMember
   * const TournamentTeamMember = await prisma.tournamentTeamMember.create({
   *   data: {
   *     // ... data to create a TournamentTeamMember
   *   }
   * })
   * 
   */
  create<T extends TournamentTeamMemberCreateArgs>(args: Prisma.SelectSubset<T, TournamentTeamMemberCreateArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamMemberClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TournamentTeamMembers.
   * @param {TournamentTeamMemberCreateManyArgs} args - Arguments to create many TournamentTeamMembers.
   * @example
   * // Create many TournamentTeamMembers
   * const tournamentTeamMember = await prisma.tournamentTeamMember.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TournamentTeamMemberCreateManyArgs>(args?: Prisma.SelectSubset<T, TournamentTeamMemberCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TournamentTeamMembers and returns the data saved in the database.
   * @param {TournamentTeamMemberCreateManyAndReturnArgs} args - Arguments to create many TournamentTeamMembers.
   * @example
   * // Create many TournamentTeamMembers
   * const tournamentTeamMember = await prisma.tournamentTeamMember.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TournamentTeamMembers and only return the `id`
   * const tournamentTeamMemberWithIdOnly = await prisma.tournamentTeamMember.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TournamentTeamMemberCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TournamentTeamMemberCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TournamentTeamMember.
   * @param {TournamentTeamMemberDeleteArgs} args - Arguments to delete one TournamentTeamMember.
   * @example
   * // Delete one TournamentTeamMember
   * const TournamentTeamMember = await prisma.tournamentTeamMember.delete({
   *   where: {
   *     // ... filter to delete one TournamentTeamMember
   *   }
   * })
   * 
   */
  delete<T extends TournamentTeamMemberDeleteArgs>(args: Prisma.SelectSubset<T, TournamentTeamMemberDeleteArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamMemberClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TournamentTeamMember.
   * @param {TournamentTeamMemberUpdateArgs} args - Arguments to update one TournamentTeamMember.
   * @example
   * // Update one TournamentTeamMember
   * const tournamentTeamMember = await prisma.tournamentTeamMember.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TournamentTeamMemberUpdateArgs>(args: Prisma.SelectSubset<T, TournamentTeamMemberUpdateArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamMemberClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TournamentTeamMembers.
   * @param {TournamentTeamMemberDeleteManyArgs} args - Arguments to filter TournamentTeamMembers to delete.
   * @example
   * // Delete a few TournamentTeamMembers
   * const { count } = await prisma.tournamentTeamMember.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TournamentTeamMemberDeleteManyArgs>(args?: Prisma.SelectSubset<T, TournamentTeamMemberDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentTeamMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentTeamMemberUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TournamentTeamMembers
   * const tournamentTeamMember = await prisma.tournamentTeamMember.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TournamentTeamMemberUpdateManyArgs>(args: Prisma.SelectSubset<T, TournamentTeamMemberUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentTeamMembers and returns the data updated in the database.
   * @param {TournamentTeamMemberUpdateManyAndReturnArgs} args - Arguments to update many TournamentTeamMembers.
   * @example
   * // Update many TournamentTeamMembers
   * const tournamentTeamMember = await prisma.tournamentTeamMember.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TournamentTeamMembers and only return the `id`
   * const tournamentTeamMemberWithIdOnly = await prisma.tournamentTeamMember.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TournamentTeamMemberUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TournamentTeamMemberUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TournamentTeamMember.
   * @param {TournamentTeamMemberUpsertArgs} args - Arguments to update or create a TournamentTeamMember.
   * @example
   * // Update or create a TournamentTeamMember
   * const tournamentTeamMember = await prisma.tournamentTeamMember.upsert({
   *   create: {
   *     // ... data to create a TournamentTeamMember
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TournamentTeamMember we want to update
   *   }
   * })
   */
  upsert<T extends TournamentTeamMemberUpsertArgs>(args: Prisma.SelectSubset<T, TournamentTeamMemberUpsertArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamMemberClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamMemberPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TournamentTeamMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentTeamMemberCountArgs} args - Arguments to filter TournamentTeamMembers to count.
   * @example
   * // Count the number of TournamentTeamMembers
   * const count = await prisma.tournamentTeamMember.count({
   *   where: {
   *     // ... the filter for the TournamentTeamMembers we want to count
   *   }
   * })
  **/
  count<T extends TournamentTeamMemberCountArgs>(
    args?: Prisma.Subset<T, TournamentTeamMemberCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TournamentTeamMemberCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TournamentTeamMember.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentTeamMemberAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TournamentTeamMemberAggregateArgs>(args: Prisma.Subset<T, TournamentTeamMemberAggregateArgs>): Prisma.PrismaPromise<GetTournamentTeamMemberAggregateType<T>>

  /**
   * Group by TournamentTeamMember.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentTeamMemberGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TournamentTeamMemberGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TournamentTeamMemberGroupByArgs['orderBy'] }
      : { orderBy?: TournamentTeamMemberGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TournamentTeamMemberGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTournamentTeamMemberGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TournamentTeamMember model
 */
readonly fields: TournamentTeamMemberFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TournamentTeamMember.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TournamentTeamMemberClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  team<T extends Prisma.TournamentTeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentTeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TournamentTeamMember model
 */
export interface TournamentTeamMemberFieldRefs {
  readonly id: Prisma.FieldRef<"TournamentTeamMember", 'String'>
  readonly teamId: Prisma.FieldRef<"TournamentTeamMember", 'String'>
  readonly userId: Prisma.FieldRef<"TournamentTeamMember", 'String'>
}
    

// Custom InputTypes
/**
 * TournamentTeamMember findUnique
 */
export type TournamentTeamMemberFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * Filter, which TournamentTeamMember to fetch.
   */
  where: Prisma.TournamentTeamMemberWhereUniqueInput
}

/**
 * TournamentTeamMember findUniqueOrThrow
 */
export type TournamentTeamMemberFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * Filter, which TournamentTeamMember to fetch.
   */
  where: Prisma.TournamentTeamMemberWhereUniqueInput
}

/**
 * TournamentTeamMember findFirst
 */
export type TournamentTeamMemberFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * Filter, which TournamentTeamMember to fetch.
   */
  where?: Prisma.TournamentTeamMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentTeamMembers to fetch.
   */
  orderBy?: Prisma.TournamentTeamMemberOrderByWithRelationInput | Prisma.TournamentTeamMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentTeamMembers.
   */
  cursor?: Prisma.TournamentTeamMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentTeamMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentTeamMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentTeamMembers.
   */
  distinct?: Prisma.TournamentTeamMemberScalarFieldEnum | Prisma.TournamentTeamMemberScalarFieldEnum[]
}

/**
 * TournamentTeamMember findFirstOrThrow
 */
export type TournamentTeamMemberFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * Filter, which TournamentTeamMember to fetch.
   */
  where?: Prisma.TournamentTeamMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentTeamMembers to fetch.
   */
  orderBy?: Prisma.TournamentTeamMemberOrderByWithRelationInput | Prisma.TournamentTeamMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentTeamMembers.
   */
  cursor?: Prisma.TournamentTeamMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentTeamMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentTeamMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentTeamMembers.
   */
  distinct?: Prisma.TournamentTeamMemberScalarFieldEnum | Prisma.TournamentTeamMemberScalarFieldEnum[]
}

/**
 * TournamentTeamMember findMany
 */
export type TournamentTeamMemberFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * Filter, which TournamentTeamMembers to fetch.
   */
  where?: Prisma.TournamentTeamMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentTeamMembers to fetch.
   */
  orderBy?: Prisma.TournamentTeamMemberOrderByWithRelationInput | Prisma.TournamentTeamMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TournamentTeamMembers.
   */
  cursor?: Prisma.TournamentTeamMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentTeamMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentTeamMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentTeamMembers.
   */
  distinct?: Prisma.TournamentTeamMemberScalarFieldEnum | Prisma.TournamentTeamMemberScalarFieldEnum[]
}

/**
 * TournamentTeamMember create
 */
export type TournamentTeamMemberCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * The data needed to create a TournamentTeamMember.
   */
  data: Prisma.XOR<Prisma.TournamentTeamMemberCreateInput, Prisma.TournamentTeamMemberUncheckedCreateInput>
}

/**
 * TournamentTeamMember createMany
 */
export type TournamentTeamMemberCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TournamentTeamMembers.
   */
  data: Prisma.TournamentTeamMemberCreateManyInput | Prisma.TournamentTeamMemberCreateManyInput[]
}

/**
 * TournamentTeamMember createManyAndReturn
 */
export type TournamentTeamMemberCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * The data used to create many TournamentTeamMembers.
   */
  data: Prisma.TournamentTeamMemberCreateManyInput | Prisma.TournamentTeamMemberCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentTeamMember update
 */
export type TournamentTeamMemberUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * The data needed to update a TournamentTeamMember.
   */
  data: Prisma.XOR<Prisma.TournamentTeamMemberUpdateInput, Prisma.TournamentTeamMemberUncheckedUpdateInput>
  /**
   * Choose, which TournamentTeamMember to update.
   */
  where: Prisma.TournamentTeamMemberWhereUniqueInput
}

/**
 * TournamentTeamMember updateMany
 */
export type TournamentTeamMemberUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TournamentTeamMembers.
   */
  data: Prisma.XOR<Prisma.TournamentTeamMemberUpdateManyMutationInput, Prisma.TournamentTeamMemberUncheckedUpdateManyInput>
  /**
   * Filter which TournamentTeamMembers to update
   */
  where?: Prisma.TournamentTeamMemberWhereInput
  /**
   * Limit how many TournamentTeamMembers to update.
   */
  limit?: number
}

/**
 * TournamentTeamMember updateManyAndReturn
 */
export type TournamentTeamMemberUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * The data used to update TournamentTeamMembers.
   */
  data: Prisma.XOR<Prisma.TournamentTeamMemberUpdateManyMutationInput, Prisma.TournamentTeamMemberUncheckedUpdateManyInput>
  /**
   * Filter which TournamentTeamMembers to update
   */
  where?: Prisma.TournamentTeamMemberWhereInput
  /**
   * Limit how many TournamentTeamMembers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentTeamMember upsert
 */
export type TournamentTeamMemberUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * The filter to search for the TournamentTeamMember to update in case it exists.
   */
  where: Prisma.TournamentTeamMemberWhereUniqueInput
  /**
   * In case the TournamentTeamMember found by the `where` argument doesn't exist, create a new TournamentTeamMember with this data.
   */
  create: Prisma.XOR<Prisma.TournamentTeamMemberCreateInput, Prisma.TournamentTeamMemberUncheckedCreateInput>
  /**
   * In case the TournamentTeamMember was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TournamentTeamMemberUpdateInput, Prisma.TournamentTeamMemberUncheckedUpdateInput>
}

/**
 * TournamentTeamMember delete
 */
export type TournamentTeamMemberDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
  /**
   * Filter which TournamentTeamMember to delete.
   */
  where: Prisma.TournamentTeamMemberWhereUniqueInput
}

/**
 * TournamentTeamMember deleteMany
 */
export type TournamentTeamMemberDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentTeamMembers to delete
   */
  where?: Prisma.TournamentTeamMemberWhereInput
  /**
   * Limit how many TournamentTeamMembers to delete.
   */
  limit?: number
}

/**
 * TournamentTeamMember without action
 */
export type TournamentTeamMemberDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeamMember
   */
  select?: Prisma.TournamentTeamMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeamMember
   */
  omit?: Prisma.TournamentTeamMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamMemberInclude<ExtArgs> | null
}
