
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Block
 * 
 */
export type Block = Prisma.BlockModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Tournament
 * 
 */
export type Tournament = Prisma.TournamentModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Forum
 * 
 */
export type Forum = Prisma.ForumModel
/**
 * Model Topic
 * 
 */
export type Topic = Prisma.TopicModel
/**
 * Model Post
 * 
 */
export type Post = Prisma.PostModel
/**
 * Model Conversation
 * 
 */
export type Conversation = Prisma.ConversationModel
/**
 * Model PrivateMessage
 * 
 */
export type PrivateMessage = Prisma.PrivateMessageModel
/**
 * Model TopicView
 * 
 */
export type TopicView = Prisma.TopicViewModel
/**
 * Model Mention
 * 
 */
export type Mention = Prisma.MentionModel
/**
 * Model PostReaction
 * 
 */
export type PostReaction = Prisma.PostReactionModel
/**
 * Model RoleConfig
 * 
 */
export type RoleConfig = Prisma.RoleConfigModel
/**
 * Model TopicFollow
 * 
 */
export type TopicFollow = Prisma.TopicFollowModel
/**
 * Model ReferenceData
 * 
 */
export type ReferenceData = Prisma.ReferenceDataModel
/**
 * Model TournamentRegistration
 * 
 */
export type TournamentRegistration = Prisma.TournamentRegistrationModel
/**
 * Model TournamentTeam
 * 
 */
export type TournamentTeam = Prisma.TournamentTeamModel
/**
 * Model TournamentTeamMember
 * 
 */
export type TournamentTeamMember = Prisma.TournamentTeamMemberModel
/**
 * Model TournamentMercenary
 * 
 */
export type TournamentMercenary = Prisma.TournamentMercenaryModel
/**
 * Model SiteSetting
 * 
 */
export type SiteSetting = Prisma.SiteSettingModel
/**
 * Model Article
 * 
 */
export type Article = Prisma.ArticleModel
/**
 * Model ArticleTag
 * 
 */
export type ArticleTag = Prisma.ArticleTagModel
/**
 * Model ArticleReaction
 * 
 */
export type ArticleReaction = Prisma.ArticleReactionModel
/**
 * Model Ligue
 * 
 */
export type Ligue = Prisma.LigueModel
/**
 * Model ModerationReport
 * 
 */
export type ModerationReport = Prisma.ModerationReportModel
/**
 * Model ModerationLog
 * 
 */
export type ModerationLog = Prisma.ModerationLogModel
/**
 * Model Resource
 * 
 */
export type Resource = Prisma.ResourceModel
/**
 * Model ResourceTag
 * 
 */
export type ResourceTag = Prisma.ResourceTagModel
/**
 * Model TournamentResult
 * 
 */
export type TournamentResult = Prisma.TournamentResultModel
/**
 * Model TournamentRound
 * 
 */
export type TournamentRound = Prisma.TournamentRoundModel
/**
 * Model TournamentMatch
 * 
 */
export type TournamentMatch = Prisma.TournamentMatchModel
