
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Accounts
 * const accounts = await prisma.account.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Block
 * 
 */
export type Block = Prisma.BlockModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Tournament
 * 
 */
export type Tournament = Prisma.TournamentModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Forum
 * 
 */
export type Forum = Prisma.ForumModel
/**
 * Model Topic
 * 
 */
export type Topic = Prisma.TopicModel
/**
 * Model Post
 * 
 */
export type Post = Prisma.PostModel
/**
 * Model Conversation
 * 
 */
export type Conversation = Prisma.ConversationModel
/**
 * Model PrivateMessage
 * 
 */
export type PrivateMessage = Prisma.PrivateMessageModel
/**
 * Model TopicView
 * 
 */
export type TopicView = Prisma.TopicViewModel
/**
 * Model Mention
 * 
 */
export type Mention = Prisma.MentionModel
/**
 * Model PostReaction
 * 
 */
export type PostReaction = Prisma.PostReactionModel
/**
 * Model RoleConfig
 * 
 */
export type RoleConfig = Prisma.RoleConfigModel
/**
 * Model TopicFollow
 * 
 */
export type TopicFollow = Prisma.TopicFollowModel
/**
 * Model ReferenceData
 * 
 */
export type ReferenceData = Prisma.ReferenceDataModel
/**
 * Model TournamentRegistration
 * 
 */
export type TournamentRegistration = Prisma.TournamentRegistrationModel
/**
 * Model TournamentTeam
 * 
 */
export type TournamentTeam = Prisma.TournamentTeamModel
/**
 * Model TournamentTeamMember
 * 
 */
export type TournamentTeamMember = Prisma.TournamentTeamMemberModel
/**
 * Model TournamentMercenary
 * 
 */
export type TournamentMercenary = Prisma.TournamentMercenaryModel
/**
 * Model SiteSetting
 * 
 */
export type SiteSetting = Prisma.SiteSettingModel
/**
 * Model Article
 * 
 */
export type Article = Prisma.ArticleModel
/**
 * Model ArticleTag
 * 
 */
export type ArticleTag = Prisma.ArticleTagModel
/**
 * Model ArticleReaction
 * 
 */
export type ArticleReaction = Prisma.ArticleReactionModel
/**
 * Model Ligue
 * 
 */
export type Ligue = Prisma.LigueModel
/**
 * Model ModerationReport
 * 
 */
export type ModerationReport = Prisma.ModerationReportModel
/**
 * Model ModerationLog
 * 
 */
export type ModerationLog = Prisma.ModerationLogModel
/**
 * Model Resource
 * 
 */
export type Resource = Prisma.ResourceModel
/**
 * Model ResourceTag
 * 
 */
export type ResourceTag = Prisma.ResourceTagModel
/**
 * Model TournamentResult
 * 
 */
export type TournamentResult = Prisma.TournamentResultModel
/**
 * Model TournamentRound
 * 
 */
export type TournamentRound = Prisma.TournamentRoundModel
/**
 * Model TournamentMatch
 * 
 */
export type TournamentMatch = Prisma.TournamentMatchModel
