
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.5.0
 * Query Engine version: 280c870be64f457428992c43c1f6d557fab6e29e
 */
Prisma.prismaVersion = {
  client: "7.5.0",
  engine: "280c870be64f457428992c43c1f6d557fab6e29e"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  role: 'role',
  nafNumber: 'nafNumber',
  region: 'region',
  league: 'league',
  signature: 'signature',
  isBanned: 'isBanned',
  banReason: 'banReason',
  avatarFrame: 'avatarFrame',
  theme: 'theme'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.TournamentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  date: 'date',
  endDate: 'endDate',
  location: 'location',
  address: 'address',
  gmapsUrl: 'gmapsUrl',
  ville: 'ville',
  departement: 'departement',
  region: 'region',
  regionNAF: 'regionNAF',
  description: 'description',
  maxParticipants: 'maxParticipants',
  currentParticipants: 'currentParticipants',
  preRegistered: 'preRegistered',
  isTeam: 'isTeam',
  coachsPerTeam: 'coachsPerTeam',
  days: 'days',
  totalMatches: 'totalMatches',
  price: 'price',
  priceMeals: 'priceMeals',
  priceLodging: 'priceLodging',
  structure: 'structure',
  lodgingAtVenue: 'lodgingAtVenue',
  ruleset: 'ruleset',
  mealsIncluded: 'mealsIncluded',
  fridayArrival: 'fridayArrival',
  gameEdition: 'gameEdition',
  platform: 'platform',
  isNAF: 'isNAF',
  isCDF: 'isCDF',
  isCGO: 'isCGO',
  isTGE: 'isTGE',
  isTSC: 'isTSC',
  organizerId: 'organizerId'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  order: 'order',
  allowedRoles: 'allowedRoles'
};

exports.Prisma.ForumScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  order: 'order',
  allowedRoles: 'allowedRoles',
  isLocked: 'isLocked',
  isTournamentForum: 'isTournamentForum',
  categoryId: 'categoryId',
  parentForumId: 'parentForumId'
};

exports.Prisma.TopicScalarFieldEnum = {
  id: 'id',
  title: 'title',
  isLocked: 'isLocked',
  isSticky: 'isSticky',
  isArchived: 'isArchived',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  views: 'views',
  forumId: 'forumId',
  authorId: 'authorId',
  tournamentId: 'tournamentId'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  topicId: 'topicId',
  authorId: 'authorId',
  isModerated: 'isModerated',
  moderationReason: 'moderationReason',
  moderatedBy: 'moderatedBy',
  isDeleted: 'isDeleted'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  user1Id: 'user1Id',
  user2Id: 'user2Id',
  user1DeletedAt: 'user1DeletedAt',
  user2DeletedAt: 'user2DeletedAt'
};

exports.Prisma.PrivateMessageScalarFieldEnum = {
  id: 'id',
  content: 'content',
  createdAt: 'createdAt',
  conversationId: 'conversationId',
  authorId: 'authorId',
  readAt: 'readAt'
};

exports.Prisma.TopicViewScalarFieldEnum = {
  userId: 'userId',
  topicId: 'topicId',
  lastViewedAt: 'lastViewedAt',
  lastPostId: 'lastPostId'
};

exports.Prisma.MentionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  postId: 'postId',
  mentionerId: 'mentionerId',
  mentionedUserId: 'mentionedUserId',
  readAt: 'readAt'
};

exports.Prisma.PostReactionScalarFieldEnum = {
  id: 'id',
  emoji: 'emoji',
  createdAt: 'createdAt',
  postId: 'postId',
  userId: 'userId'
};

exports.Prisma.RoleConfigScalarFieldEnum = {
  name: 'name',
  label: 'label',
  color: 'color',
  power: 'power',
  isBaseRole: 'isBaseRole',
  updatedAt: 'updatedAt'
};

exports.Prisma.TopicFollowScalarFieldEnum = {
  userId: 'userId',
  topicId: 'topicId'
};

exports.Prisma.ReferenceDataScalarFieldEnum = {
  id: 'id',
  group: 'group',
  key: 'key',
  label: 'label',
  order: 'order',
  isActive: 'isActive'
};

exports.Prisma.TournamentRegistrationScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  userId: 'userId',
  status: 'status',
  paymentStatus: 'paymentStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TournamentTeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  tournamentId: 'tournamentId',
  captainId: 'captainId',
  status: 'status',
  paymentStatus: 'paymentStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TournamentTeamMemberScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  userId: 'userId'
};

exports.Prisma.TournamentMercenaryScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.SiteSettingScalarFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.RegistrationStatus = exports.$Enums.RegistrationStatus = {
  PRE_REGISTERED: 'PRE_REGISTERED',
  REGISTERED: 'REGISTERED',
  WAITING_LIST: 'WAITING_LIST'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  NOT_PAID: 'NOT_PAID',
  PAID: 'PAID',
  AT_TOURNAMENT: 'AT_TOURNAMENT',
  GUEST: 'GUEST',
  DEPANNAGE: 'DEPANNAGE'
};

exports.Prisma.ModelName = {
  Account: 'Account',
  Session: 'Session',
  User: 'User',
  VerificationToken: 'VerificationToken',
  Tournament: 'Tournament',
  Category: 'Category',
  Forum: 'Forum',
  Topic: 'Topic',
  Post: 'Post',
  Conversation: 'Conversation',
  PrivateMessage: 'PrivateMessage',
  TopicView: 'TopicView',
  Mention: 'Mention',
  PostReaction: 'PostReaction',
  RoleConfig: 'RoleConfig',
  TopicFollow: 'TopicFollow',
  ReferenceData: 'ReferenceData',
  TournamentRegistration: 'TournamentRegistration',
  TournamentTeam: 'TournamentTeam',
  TournamentTeamMember: 'TournamentTeamMember',
  TournamentMercenary: 'TournamentMercenary',
  SiteSetting: 'SiteSetting'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
